#!/bin/sh

# Dependencias

# KF5KIOWidgets
# KF5SonnetUi
# KF5TextEditor
# KF6KIOWidgets
# KF6TextEditor
# Qt5Widgets
# Qt5Designer
# Qt6Designer
# Qt6Widgets

# tput reset && buscar_simbolo /usr/lib 1 $(/opt/ida-free/ida64 2>&1 | sed "s/[,:]/\n/g" | grep _Z)

# x=fs.readFileSync(`/bin/reparar_ida`).toString()
# x.split(/\n{2}/g).slice(6).sort((a,b)=>a<b?1:a>b?-1:0).map(x=>console.log(x,"\n"))

# Tiempo reparación: 4 minutos

# 
# __cxa_throw_bad_array_new_length

p=/opt/ida-free/ida64
r=reemplazar_simbolo
o="$r $p"

$o _ZdlPvm \
      is_bnot

$o _ZN2QT12QSvgRendererC1ERKNS_7QStringEPNS_7QObjectE \
      _ZN12QSvgRendererC1ERK7QStringP7QObject

$o _ZN2QT7QAction12setCheckableEb \
      _ZN7QAction12setCheckableEb

$o _ZN2QT9QTextEdit11setReadOnlyEb \
      _ZN9QTextEdit11setReadOnlyEb

$o _ZN2QT7QWidget12setFixedSizeERKNS_5QSizeE \
      _ZN7QWidget12setFixedSizeERK5QSize

$o _ZN2QT11QDockWidget11setFeaturesENS_6QFlagsINS0_17DockWidgetFeatureEEE \
      _ZN11QDockWidget11setFeaturesE6QFlagsINS_17DockWidgetFeatureEE

$o _ZN2QT10QBoxLayout9addLayoutEPNS_7QLayoutEi \
      _ZN10QBoxLayout9addLayoutEP7QLayouti

$o _ZN2QT6QLabel9setPixmapERKNS_7QPixmapE \
      _ZN6QLabel9setPixmapERK7QPixmap

$o _ZN2QT11QFormLayout20setFieldGrowthPolicyENS0_17FieldGrowthPolicyE \
      _ZN11QFormLayout20setFieldGrowthPolicyENS_17FieldGrowthPolicyE

$o _ZN2QT7QWidget14setMinimumSizeEii \
      _ZN7QWidget14setMinimumSizeEii

$o _ZN2QT14QPlainTextEditD2Ev \
      _ZN14QPlainTextEditD2Ev

$o _ZN2QT16QTableWidgetItemC1Ei \
      _ZN16QTableWidgetItemC1Ei

$o _ZN2QT15QAbstractSlider10setMaximumEi \
      _ZN15QAbstractSlider10setMaximumEi

$o _ZN2QT7QWidget6resizeERKNS_5QSizeE \
      _ZN7QWidget6resizeERK5QSize

$o _ZN2QT6QBrushC1ERKNS_6QColorENS_2Qt10BrushStyleE \
      _ZN6QBrushC1ERK6QColorN2Qt10BrushStyleE

$o _ZN2QT8QPainter13setRenderHintENS0_10RenderHintEb \
      _ZN8QPainter13setRenderHintENS_10RenderHintEb

$o _ZNK2QT5QFont6familyEv \
      _ZNK5QFont6familyEv

$o _ZN2QT11QMouseEventD1Ev \
      _ZN11QMouseEventD1Ev

$o _ZN2QT8QPainter11setClippingEb \
      _ZN8QPainter11setClippingEb

$o _ZN2QT7QStringaSENS_5QCharE \
      _ZN7QStringaSE5QChar

$o _ZNK2QT5QRect8containsERKNS_6QPointEb \
      _ZNK5QRect8containsERK6QPointb

$o _ZNK2QT8QVariant9constDataEv \
      _ZNK8QVariant9constDataEv

$o _ZN2QT5QFileD1Ev \
      _ZN5QFileD1Ev

$o _ZNK2QT7QString5splitERKS0_NS_6QFlagsINS_2Qt18SplitBehaviorFlagsEEENS4_15CaseSensitivityE \
      _ZNK7QString5splitERKS_6QFlagsIN2Qt18SplitBehaviorFlagsEENS3_15CaseSensitivityE

echo $LINENO

$o _ZN2QT16QCoreApplication16sendPostedEventsEPNS_7QObjectEi \
      _ZN16QCoreApplication16sendPostedEventsEP7QObjecti

$o _ZNK2QT5QIcon8cacheKeyEv \
      _ZNK5QIcon8cacheKeyEv

$o _ZN2QT11QHeaderView19setDefaultAlignmentENS_6QFlagsINS_2Qt13AlignmentFlagEEE \
      _ZN11QHeaderView19setDefaultAlignmentE6QFlagsIN2Qt13AlignmentFlagEE

$o _ZNK2QT14QItemSelection7indexesEv \
		 _ZNK14QItemSelection7indexesEv

$o _ZN2QT7QString7replaceERKNS_7QRegExpERKS0_ \
      _ZN7QString7replaceERK7QRegExpRKS_

$o _ZN2QT9QLineEditC2EPNS_7QWidgetE \
      _ZN9QLineEditC2EP7QWidget

$o _ZNK2QT13QTextDocument3endEv \
      _ZNK13QTextDocument3endEv

$o _ZN2QT11QMessageBoxC2EPNS_7QWidgetE \
      _ZN11QMessageBoxC2EP7QWidget

$o _ZN2QT11QMessageBox13keyPressEventEPNS_9QKeyEventE \
      _ZN11QMessageBox13keyPressEventEP9QKeyEvent

$o _ZN2QT14QPlainTextEdit25createStandardContextMenuERKNS_6QPointE \
      _ZN14QPlainTextEdit25createStandardContextMenuERK6QPoint

$o _ZN2QT21QTextDocumentFragmentD1Ev \
      _ZN21QTextDocumentFragmentD1Ev

$o _ZN2QT11QPushButton10setDefaultEb \
      _ZN11QPushButton10setDefaultEb

$o _ZNK2QT11QHeaderView18sortIndicatorOrderEv \
      _ZNK11QHeaderView18sortIndicatorOrderEv

$o _ZN2QT9QSettingsC1ERKNS_7QStringES3_PNS_7QObjectE \
      _ZN9QSettingsC1ERK7QStringS2_P7QObject

$o _ZN2QT7QWidget14setMaximumSizeEii \
      _ZN7QWidget14setMaximumSizeEii

$o _ZN2QT7QStringC1ENS_5QCharE \
      _ZN7QStringC1E5QChar

$o _ZN2QT7QObject10disconnectEPKS0_PKcS2_S4_ \
      _ZN7QObject10disconnectEPKS_PKcS1_S3_

$o _ZNK2QT7QString11lastIndexOfENS_5QCharEiNS_2Qt15CaseSensitivityE \
      _ZNK7QString11lastIndexOfE5QChariN2Qt15CaseSensitivityE

$o _ZN2QT13QElapsedTimer5startEv \
      _ZN13QElapsedTimer5startEv

$o _ZN2QT11QMessageBox8criticalEPNS_7QWidgetERKNS_7QStringES5_NS_6QFlagsINS0_14StandardButtonEEES7_ \
      _ZN11QMessageBox8criticalEP7QWidgetRK7QStringS4_6QFlagsINS_14StandardButtonEES6_

$o _ZNK2QT7QPixmap16devicePixelRatioEv \
      _ZNK7QPixmap16devicePixelRatioEv

$o _ZN2QT11QScrollAreaD2Ev \
      _ZN11QScrollAreaD2Ev

$o _ZN2QT6QStyle10visualRectENS_2Qt15LayoutDirectionERKNS_5QRectES5_ \
      _ZN6QStyle10visualRectEN2Qt15LayoutDirectionERK5QRectS4_

$o _ZN2QT11QTextStreamlsERKNS_7QStringE \
      _ZN11QTextStreamlsERK7QString

$o _ZN2QT15QAbstractButton5clickEv \
      _ZN15QAbstractButton5clickEv

$o _ZN2QT5QMenuC2EPNS_7QWidgetE \
      _ZN5QMenuC1EP7QWidget

$o _ZNK2QT10QTableView16horizontalHeaderEv \
      _ZNK10QTableView16horizontalHeaderEv

$o _ZN2QT8QPainter9drawRectsEPKNS_6QRectFEi \
      _ZN8QPainter9drawRectsEPK6QRectFi

$o _ZN2QT11QAccessible14installFactoryEPFPNS_20QAccessibleInterfaceERKNS_7QStringEPNS_7QObjectEE \
      _ZN11QAccessible14installFactoryEPFP20QAccessibleInterfaceRK7QStringP7QObjectE

$o _ZN2QT4QPenD1Ev \
      _ZN4QPenD1Ev

$o _ZN2QT7QString6numberEii \
      _ZN7QString6numberEii

$o _ZN2QT16QKeySequenceEdit5clearEv \
      _ZN16QKeySequenceEdit5clearEv

$o _ZN2QT29qt_set_sequence_auto_mnemonicEb \
       _Z29qt_set_sequence_auto_mnemonicb

echo $LINENO

$o _ZN2QT11QFontDialogC2EPNS_7QWidgetE \
      _ZN11QFontDialogC2EP7QWidget

$o _ZNK2QT18QSyntaxHighlighter17currentBlockStateEv \
      _ZNK18QSyntaxHighlighter17currentBlockStateEv

$o _ZN2QT8QVariantC1ERKNS_5QSizeE \
      _ZN8QVariantC1ERK5QSize

$o _ZNK2QT13QFontMetricsF16averageCharWidthEv \
      _ZNK13QFontMetricsF16averageCharWidthEv

$o _ZN2QT11QAccessible8isActiveEv \
      _ZN11QAccessible8isActiveEv

$o _ZN2QT12QApplicationD2Ev \
      _ZN12QApplicationD2Ev

$o _ZN2QT9QComboBox11setEditableEb \
      _ZN9QComboBox11setEditableEb

$o _ZN2QT12QPrintDialog4execEv \
      _ZN12QPrintDialog4execEv

$o _ZNK2QT11QMetaObject10Connection18isConnected_helperEv \
      _ZNK11QMetaObject10Connection18isConnected_helperEv

$o _ZN2QT9QLineEdit12setSelectionEii \
      _ZN9QLineEdit12setSelectionEii

$o _ZN2QT15QAbstractSlider13setSingleStepEi \
      _ZN15QAbstractSlider13setSingleStepEi

$o _ZN2QT11QPushButton11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN11QPushButton11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT6QLabelC2EPNS_7QWidgetENS_6QFlagsINS_2Qt10WindowTypeEEE \
      _ZN6QLabelC1EP7QWidget6QFlagsIN2Qt10WindowTypeEE

$o _ZN2QT11QMessageBox11qt_metacastEPKc \
      _ZN11QMessageBox11qt_metacastEPKc

$o _ZN2QT8QPainter9drawImageERKNS_7QPointFERKNS_6QImageE \
      _ZN8QPainter9drawImageERK7QPointFRK6QImage

$o _ZN2QT5QFontaSERKS0_ \
      _ZN5QFontaSERKS_

$o _ZNK2QT7QPixmap11transformedERKNS_10QTransformENS_2Qt18TransformationModeE \
      _ZNK7QPixmap11transformedERK10QTransformN2Qt18TransformationModeE

$o _ZN2QT7QWidget21setAutoFillBackgroundEb \
      _ZN7QWidget21setAutoFillBackgroundEb

$o _ZNK2QT9QSplitter11handleWidthEv \
      _ZNK9QSplitter11handleWidthEv

$o _ZNK2QT7QWidget8baseSizeEv \
      _ZNK7QWidget8baseSizeEv

$o _ZN2QT10QTabWidget13setTabVisibleEib \
      _ZN10QTabWidget13setTabVisibleEib

$o _ZN2QT7QPixmapC1ERKNS_7QStringEPKcNS_6QFlagsINS_2Qt19ImageConversionFlagEEE \
      _ZN7QPixmapC1ERK7QStringPKc6QFlagsIN2Qt19ImageConversionFlagEE

$o _ZN2QT7QLocaleD1Ev \
      _ZN7QLocaleD1Ev

$o _ZN2QT11QTextCursorD1Ev \
      _ZN11QTextCursorD1Ev

$o _ZN2QT19QStyledItemDelegateC2EPNS_7QObjectE \
      _ZN19QStyledItemDelegateC2EP7QObject

$o _ZN2QT12QTableWidgetC1EPNS_7QWidgetE \
      _ZN12QTableWidgetC1EP7QWidget

$o _ZNK2QT11QMetaObject6methodEi \
      _ZNK11QMetaObject6methodEi

$o _ZNK2QT12QMapNodeBase12previousNodeEv \
      _ZNK12QMapNodeBase12previousNodeEv

$o _ZNK2QT13QFontMetricsF17horizontalAdvanceENS_5QCharE \
      _ZNK13QFontMetricsF17horizontalAdvanceE5QChar

$o _ZN2QT5QMenu15insertSeparatorEPNS_7QActionE \
      _ZN5QMenu15insertSeparatorEP7QAction

$o _ZN2QT17QAccessibleWidgetD2Ev \
      _ZN17QAccessibleWidgetD2Ev

$o _ZN2QT7QString14compare_helperEPKNS_5QCharEiPKciNS_2Qt15CaseSensitivityE \
      _ZN7QString14compare_helperEPK5QChariPKciN2Qt15CaseSensitivityE

echo $LINENO

$o _ZN2QT10QTabWidgetC1EPNS_7QWidgetE \
      _ZN10QTabWidgetC1EP7QWidget

$o _ZNK2QT7QString5rightEi \
      _ZNK7QString5rightEi

$o _ZN2QT6QColorC1ENS_2Qt11GlobalColorE \
      _ZN6QColorC1EN2Qt11GlobalColorE

$o _ZN2QT11QMetaObject18connectSlotsByNameEPNS_7QObjectE \
      _ZN11QMetaObject18connectSlotsByNameEP7QObject

$o _ZN2QT11QMetaObject18connectSlotsByNameEPNS_7QObjectE \
      _ZN11QMetaObject18connectSlotsByNameEP7QObject

$o _ZN2QT7QTabBar20setUsesScrollButtonsEb \
      _ZN7QTabBar20setUsesScrollButtonsEb

$o _ZN2QT12QRadioButtonC1ERKNS_7QStringEPNS_7QWidgetE \
      _ZN12QRadioButtonC1ERK7QStringP7QWidget

$o _ZN2QT8QPainter6setPenENS_2Qt8PenStyleE \
      _ZN8QPainter6setPenEN2Qt8PenStyleE

$o _ZN2QT10QClipboard7setTextERKNS_7QStringENS0_4ModeE \
      _ZN10QClipboard7setTextERK7QStringNS_4ModeE

$o _ZNK2QT14QStackedWidget5countEv \
      _ZNK14QStackedWidget5countEv

$o _ZN2QT8QPainter8fillRectERKNS_6QRectFERKNS_6QBrushE \
      _ZN8QPainter8fillRectERK6QRectFRK6QBrush

$o _ZN2QT14QReadWriteLock12lockForWriteEv \
      _ZN14QReadWriteLock12lockForWriteEv

$o _ZN2QT12QMapDataBase18recalcMostLeftNodeEv \
      _ZN12QMapDataBase18recalcMostLeftNodeEv

$o _ZNK2QT11QTextFormat13brushPropertyEi \
      _ZNK11QTextFormat13brushPropertyEi

$o _ZNK2QT5QFont9styleNameEv \
      _ZNK5QFont9styleNameEv

$o _ZNK2QT19QStyledItemDelegate15initStyleOptionEPNS_20QStyleOptionViewItemERKNS_11QModelIndexE \
      _ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex

$o _ZNK2QT11QTextCursor8positionEv \
      _ZNK11QTextCursor8positionEv

$o _ZN2QT9QCheckBox11qt_metacastEPKc \
      _ZN9QCheckBox11qt_metacastEPKc

$o _ZN2QT9QLineEdit14setTextMarginsEiiii \
      _ZN9QLineEdit14setTextMarginsEiiii

$o _ZNK2QT9QTextLine15naturalTextRectEv \
      _ZNK9QTextLine15naturalTextRectEv

$o _ZNK2QT11QMetaObject11indexOfSlotEPKc \
      _ZNK11QMetaObject11indexOfSlotEPKc

$o _ZN2QT5QFont12setStrikeOutEb \
      _ZN5QFont12setStrikeOutEb

$o _ZNK2QT10QTabWidget12isTabVisibleEi \
      _ZNK10QTabWidget12isTabVisibleEi

$o _ZNK2QT7QWidget3posEv \
      _ZNK7QWidget3posEv

$o _ZN2QT9QFontInfoC1ERKNS_5QFontE \
      _ZN9QFontInfoC1ERK5QFont

$o _ZN2QT5QMenu4execERKNS_6QPointEPNS_7QActionE \
      _ZN5QMenu4execERK6QPointP7QAction

$o _ZN2QT7QWidget11grabGestureENS_2Qt11GestureTypeENS_6QFlagsINS1_11GestureFlagEEE \
      _ZN7QWidget11grabGestureEN2Qt11GestureTypeE6QFlagsINS0_11GestureFlagEE

$o _ZN2QT6QTimerC1EPNS_7QObjectE \
      _ZN6QTimerC1EP7QObject

$o _ZN2QT16QDialogButtonBox16setCenterButtonsEb \
      _ZN16QDialogButtonBox16setCenterButtonsEb

$o _ZN2QT11QTextCursor12endEditBlockEv \
      _ZN11QTextCursor12endEditBlockEv

$o _ZN2QT4QPen14setDashPatternERKNS_7QVectorIdEE \
      _ZN4QPen14setDashPatternERK7QVectorIdE

$o _ZN2QT5QMenu11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN5QMenu11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT10QStatusBar9addWidgetEPNS_7QWidgetEi \
      _ZN10QStatusBar9addWidgetEP7QWidgeti

echo $LINENO

$o _ZN2QT12QColorDialog8getColorERKNS_6QColorEPNS_7QWidgetERKNS_7QStringENS_6QFlagsINS0_17ColorDialogOptionEEE \
      _ZN12QColorDialog8getColorERK6QColorP7QWidgetRK7QString6QFlagsINS_17ColorDialogOptionEE

$o _ZN2QT9QLineEdit11setEchoModeENS0_8EchoModeE \
      _ZN9QLineEdit11setEchoModeENS_8EchoModeE

$o _ZN2QT9QComboBox11setLineEditEPNS_9QLineEditE \
      _ZN9QComboBox11setLineEditEP9QLineEdit

$o _ZN2QT6QLabelC2ERKNS_7QStringEPNS_7QWidgetENS_6QFlagsINS_2Qt10WindowTypeEEE \
      _ZN6QLabelC1ERK7QStringP7QWidget6QFlagsIN2Qt10WindowTypeEE

$o _ZN2QT9QLineEdit11qt_metacastEPKc \
      _ZN9QLineEdit11qt_metacastEPKc

$o _ZN2QT15QAbstractSlider8setValueEi \
      _ZN15QAbstractSlider8setValueEi

$o _ZNK2QT9QLineEdit9completerEv \
      _ZNK9QLineEdit9completerEv

$o _ZN2QT10QScrollBarD2Ev \
      _ZN10QScrollBarD2Ev

$o _ZN2QT5QFont9setFamilyERKNS_7QStringE \
      _ZN5QFont9setFamilyERK7QString

$o _ZN2QT11QTextLayoutD1Ev \
      _ZN11QTextLayoutD1Ev

$o _ZN2QT8QVariantC1ENS_13QLatin1StringE \
      _ZN8QVariantC1E13QLatin1String

$o _ZN2QT18QSyntaxHighlighter11rehighlightEv \
      _ZN18QSyntaxHighlighter11rehighlightEv

$o _ZNK2QT19QStyledItemDelegate8sizeHintERKNS_20QStyleOptionViewItemERKNS_11QModelIndexE \
      _ZNK19QStyledItemDelegate8sizeHintERK20QStyleOptionViewItemRK11QModelIndex

$o _ZNK2QT7QTabBar12currentIndexEv \
      _ZNK7QTabBar12currentIndexEv

$o _ZNK2QT9QLineEdit14cursorPositionEv \
      _ZNK9QLineEdit14cursorPositionEv

$o _ZN2QT17QFileIconProviderD1Ev \
      _ZN17QFileIconProviderD1Ev

$o _ZN2QT12QKeySequence11keyBindingsENS0_11StandardKeyE \
      _ZN12QKeySequence11keyBindingsENS_11StandardKeyE

$o _ZN2QT7QRegionC1ERKNS_5QRectENS0_10RegionTypeE \
      _ZN7QRegionC1ERK5QRectNS_10RegionTypeE

$o _ZN2QT8QVariantC1ERKNS_10QByteArrayE \
         _ZN8QVariantC1ERK10QByteArray

$o _ZN2QT9QCheckBox11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN9QCheckBox11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT10QTableViewD2Ev \
      _ZN10QTableViewD2Ev

$o _ZN2QT10QCompleter17setCompletionModeENS0_14CompletionModeE \
       _ZN10QCompleter17setCompletionModeENS_14CompletionModeE

$o _ZN2QT10QCompleter18setCaseSensitivityENS_2Qt15CaseSensitivityE \
        _ZN10QCompleter18setCaseSensitivityEN2Qt15CaseSensitivityE

$o _ZN2QT11QDataStreamrsERa \
      _ZN11QDataStreamrsERa

$o _ZN2QT20QStyleOptionViewItemC1Ev \
      _ZN20QStyleOptionViewItemC1Ev

$o _ZN2QT17QAbstractItemView14clearSelectionEv \
      _ZN17QAbstractItemView14clearSelectionEv

$o _ZN2QT13QFontMetricsFC1ERKNS_12QFontMetricsE \
      _ZN13QFontMetricsFC1ERK12QFontMetrics

$o _ZN2QT5QTime11currentTimeEv \
      _ZN5QTime11currentTimeEv

$o _ZNK2QT8QVariant10canConvertEi \
      _ZNK8QVariant10canConvertEi

$o _ZN2QT10QTableView17setSortingEnabledEb \
      _ZN10QTableView17setSortingEnabledEb

$o _ZNK2QT11QFontDialog11currentFontEv \
      _ZNK11QFontDialog11currentFontEv

$o _ZN2QT8QPrinterD1Ev \
      _ZN8QPrinterD1Ev

$o _ZNK2QT8QVariant7convertEiPv \
      _ZNK8QVariant7convertEiPv

echo $LINENO

$o _ZN2QT7QString9fromUtf16EPKti \
      _ZN7QString9fromUtf16EPKti

$o _ZN2QT6QFrameD2Ev \
      _ZN6QFrameD2Ev

$o _ZNK2QT9QFileInfo8fileNameEv \
      _ZNK9QFileInfo8fileNameEv

$o _ZNK2QT15QAbstractButton5groupEv \
      _ZNK15QAbstractButton5groupEv

$o _ZN2QT7QAction10setCheckedEb \
      _ZN7QAction10setCheckedEb

$o _ZNK2QT10QTabWidget13currentWidgetEv \
      _ZNK10QTabWidget13currentWidgetEv

$o _ZNK2QT10QTextBlock7isValidEv \
      _ZNK10QTextBlock7isValidEv

$o _ZN2QT7QWidget14activateWindowEv \
      _ZN7QWidget14activateWindowEv

$o _ZN2QT9QLineEditC2EPNS_7QWidgetE \
      _ZN9QLineEditC2EP7QWidget

$o _ZNK2QT7QString7indexOfENS_5QCharEiNS_2Qt15CaseSensitivityE \
      _ZNK7QString7indexOfE5QChariN2Qt15CaseSensitivityE

$o _ZN2QT15QGuiApplication12mouseButtonsEv \
      _ZN15QGuiApplication12mouseButtonsEv

$o _ZNK2QT5QFont10pointSizeFEv \
      _ZNK5QFont10pointSizeFEv

$o _ZNK2QT8QProcess5stateEv \
      _ZNK8QProcess5stateEv

$o _ZNK2QT7QWidget12contentsRectEv \
      _ZNK7QWidget12contentsRectEv

$o _ZN2QT7QObject14disconnectImplEPKS0_PPvS2_S4_PKNS_11QMetaObjectE \
      _ZN7QObject14disconnectImplEPKS_PPvS1_S3_PK11QMetaObject

$o _ZNK2QT6QColor7lighterEi \
      _ZNK6QColor7lighterEi

$o _ZN2QT8QProcess9terminateEv \
      _ZN8QProcess9terminateEv

$o _ZN2QT7QWidget7repaintEv \
      _ZN7QWidget7repaintEv

$o _ZNK2QT7QString11lastIndexOfERKS0_iNS_2Qt15CaseSensitivityE \
      _ZNK7QString11lastIndexOfERKS_iN2Qt15CaseSensitivityE

$o _ZN2QT10QByteArray6appendEPKc \
      _ZN10QByteArray6appendEc

$o _ZN2QT8QToolBar9addWidgetEPNS_7QWidgetE \
      _ZN8QToolBar9addWidgetEP7QWidget

$o _ZN2QT5QChar7isPrintEj \
      _ZN5QChar7isPrintEj

$o _ZNK2QT9QFontInfo6weightEv \
      _ZNK9QFontInfo6weightEv

$o _ZN2QT6QImageC1Ev \
      _ZN6QImageC1Ev

$o _ZNK2QT9QMimeData4urlsEv \
      _ZNK9QMimeData4urlsEv

$o _ZN2QT11QTreeWidgetC2EPNS_7QWidgetE \
      _ZN11QTreeWidgetC2EP7QWidget

$o _ZNK2QT7QCursorcvNS_8QVariantEEv \
      _ZNK7QCursorcv8QVariantEv

$o _ZN2QT5QMenu11qt_metacastEPKc \
      _ZN5QMenu11qt_metacastEPKc

$o _ZN2QT11QListWidgetC1EPNS_7QWidgetE \
      _ZN11QListWidgetC1EP7QWidget

$o _ZNK2QT5QMenu7isEmptyEv \
      _ZNK5QMenu7isEmptyEv

$o _ZN2QT7QWidget14setWindowTitleERKNS_7QStringE \
      _ZN7QWidget14setWindowTitleERK7QString

$o _ZNK2QT11QTranslator9translateEPKcS2_S2_i \
      _ZNK11QTranslator9translateEPKcS1_S1_i

echo $LINENO

$o _ZN2QT10QByteArray11reallocDataEjNS_6QFlagsINS_10QArrayData16AllocationOptionEEE \
      _ZN10QByteArray11reallocDataEj6QFlagsIN10QArrayData16AllocationOptionEE

$o _ZN2QT10QTableView9selectRowEi \
      _ZN10QTableView9selectRowEi

$o _ZNK2QT9QSplitter7indexOfEPNS_7QWidgetE \
      _ZNK9QSplitter7indexOfEP7QWidget

$o _ZNK2QT9QSplitter7indexOfEPNS_7QWidgetE \
      _ZNK9QSplitter7indexOfEP7QWidget

$o _ZN2QT12QApplication12activeWindowEv \
      _ZN12QApplication12activeWindowEv

$o _ZN2QT11QTextStream7readAllEv \
      _ZN11QTextStream7readAllEv

$o _ZN2QT8QPalette8setBrushENS0_10ColorGroupENS0_9ColorRoleERKNS_6QBrushE \
      _ZN8QPalette8setBrushENS_10ColorGroupENS_9ColorRoleERK6QBrush

$o _ZNK2QT12QFontMetrics6heightEv \
      _ZNK12QFontMetrics6heightEv

$o _ZNK2QT7QString7compareERKS0_NS_2Qt15CaseSensitivityE \
      _ZNK7QString7compareERKS_N2Qt15CaseSensitivityE

$o _ZNK2QT11QHeaderView11orientationEv \
      _ZNK11QHeaderView11orientationEv

$o _ZN2QT11QTextCursor10insertTextERKNS_7QStringE \
      _ZN11QTextCursor10insertTextERK7QString

$o _ZN2QT11QPushButton7setFlatEb \
      _ZN11QPushButton7setFlatEb

$o _ZN2QT7QString14toLower_helperERS0_ \
      _ZN7QString14toLower_helperERS_

$o _ZN2QT9QGroupBoxD2Ev \
      _ZN9QGroupBoxD2Ev

$o _ZNK2QT8QGesture5stateEv \
      _ZNK8QGesture5stateEv

$o _ZNK2QT13QElapsedTimer7isValidEv \
      _ZNK13QElapsedTimer7isValidEv

$o _ZN2QT6QLabel8setBuddyEPNS_7QWidgetE \
      _ZN6QLabel8setBuddyEP7QWidget

$o _ZN2QT5QMenuD1Ev \
      _ZN5QMenuD1Ev

$o _ZN2QT11QMainWindow10addToolBarEPNS_8QToolBarE \
      _ZN11QMainWindow10addToolBarEP8QToolBar

$o _ZN2QT7QObject11connectImplEPKS0_PPvS2_S4_PNS_9QtPrivate15QSlotObjectBaseENS_2Qt14ConnectionTypeEPKiPKNS_11QMetaObjectE \
      _ZN7QObject11connectImplEPKS_PPvS1_S3_PN9QtPrivate15QSlotObjectBaseEN2Qt14ConnectionTypeEPKiPK11QMetaObject

$o _ZNK2QT7QWindow16devicePixelRatioEv \
      _ZNK7QWindow16devicePixelRatioEv

$o _ZNK2QT7QAction9isCheckedEv \
      _ZNK7QAction9isCheckedEv

$o _ZN2QT7QDialog11qt_metacastEPKc \
      _ZN7QDialog11qt_metacastEPKc

$o _ZN2QT18QSyntaxHighlighterD2Ev \
      _ZN18QSyntaxHighlighterD2Ev

$o _ZNK2QT5QMenu12activeActionEv \
      _ZNK5QMenu12activeActionEv

$o _ZN2QTeqERKNS_7QStringES2_ \
           _ZeqRK7QStringS1_

$o _ZN2QT18QSyntaxHighlighterC2EPNS_7QObjectE \
      _ZN18QSyntaxHighlighterC2EP7QObject

$o _ZN2QT7QString8truncateEi \
      _ZN7QString8truncateEi

$o _ZNK2QT14QStackedWidget6widgetEi \
      _ZNK14QStackedWidget6widgetEi

$o _ZN2QT7QTabBar11qt_metacastEPKc \
      _ZN7QTabBar11qt_metacastEPKc

$o _ZNK2QT14QPlainTextEdit21blockBoundingGeometryERKNS_10QTextBlockE \
      _ZNK14QPlainTextEdit21blockBoundingGeometryERK10QTextBlock

$o _ZN2QT14QPlainTextEditC1EPNS_7QWidgetE \
      _ZN14QPlainTextEditC1EP7QWidget

$o _ZN2QT7QString6insertEiPKNS_5QCharEi \
         _ZN7QString6insertEiPK5QChari

echo $LINENO

$o _ZN2QT4QDir18toNativeSeparatorsERKNS_7QStringE \
      _ZN4QDir18toNativeSeparatorsERK7QString

$o _ZN2QT7QObject11deleteLaterEv \
      _ZN7QObject11deleteLaterEv

$o _ZNK2QT9QComboBox8itemDataEii \
      _ZNK9QComboBox8itemDataEii

$o _ZN2QT7QWidget20setContextMenuPolicyENS_2Qt17ContextMenuPolicyE \
      _ZN7QWidget20setContextMenuPolicyEN2Qt17ContextMenuPolicyE

$o _ZN2QT5QFont12setPixelSizeEi \
      _ZN5QFont12setPixelSizeEi

$o _ZN2QT8QVariantC1Eb \
      _ZN8QVariantC1Eb

$o _ZN2QT9QListData6removeEi \
      _ZN9QListData6removeEi

$o _ZN2QT11QGridLayout18setVerticalSpacingEi \
      _ZN11QGridLayout18setVerticalSpacingEi

$o _ZN2QT16QDialogButtonBox9addButtonENS0_14StandardButtonE \
      _ZN16QDialogButtonBox9addButtonENS_14StandardButtonE

$o _ZNK2QT6QColor4rgbaEv \
      _ZNK6QColor4rgbaEv

$o _ZN2QT9QMetaType8typeNameEi \
      _ZN9QMetaType8typeNameEi

$o _ZN2QT7QString6numberEji \
      _ZN7QString6numberEji

$o _ZNK2QT5QFont6weightEv \
      _ZNK5QFont6weightEv

$o _ZNK2QT9QComboBox4viewEv \
      _ZNK9QComboBox4viewEv

$o _ZNK2QT7QWidget12isFullScreenEv \
      _ZNK7QWidget12isFullScreenEv

$o _ZN2QT7QString16fromAscii_helperEPKci \
      _ZN7QString16fromAscii_helperEPKci

$o _ZN2QT13QElapsedTimer10invalidateEv \
      _ZN13QElapsedTimer10invalidateEv

$o _ZN2QT7QWidget16setMaximumHeightEi \
      _ZN7QWidget16setMaximumHeightEi

$o _ZN2QT19QStyledItemDelegateD2Ev \
      _ZN19QStyledItemDelegateD2Ev

$o _ZN2QT12QFontMetricsD1Ev \
      _ZN12QFontMetricsD1Ev

$o _ZN2QT7QString7replaceEiiNS_5QCharE \
         _ZN7QString7replaceEii5QChar

$o _ZN2QT9QGradient10setColorAtEdRKNS_6QColorE \
      _ZN9QGradient10setColorAtEdRK6QColor

$o _ZNK2QT8QVariant4typeEv \
      _ZNK8QVariant4typeEv

$o _ZN2QT12QMapDataBase8freeTreeEPNS_12QMapNodeBaseEi \
      _ZN12QMapDataBase8freeTreeEP12QMapNodeBasei

$o _ZN2QT13QSignalMapper10setMappingEPNS_7QObjectERKNS_7QStringE \
      _ZN13QSignalMapper10setMappingEP7QObjectRK7QString

$o _ZNK2QT5QFontneERKS0_ \
      _ZNK5QFontneERKS_

$o _ZN2QT5QChar10digitValueEj \
      _ZN5QChar10digitValueEj

$o _ZNK2QT7QLayout16totalMinimumSizeEv \
      _ZNK7QLayout16totalMinimumSizeEv

$o _ZN2QT11QMetaObject14normalizedTypeEPKc \
      _ZN11QMetaObject14normalizedTypeEPKc

$o _ZN2QT6QColorC1Ej \
      _ZN6QColorC1Ej

$o _ZN2QT11QAccessible19updateAccessibilityEPNS_16QAccessibleEventE \
      _ZN11QAccessible19updateAccessibilityEP16QAccessibleEvent

$o _ZN2QT11QTextStreamlsEc \
      _ZN11QTextStreamlsEc

$o _ZN2QT7QWidget6updateERKNS_5QRectE \
      _ZN7QWidget6updateERK5QRect

echo $LINENO

$o _ZN2QT16QCoreApplication12setAttributeENS_2Qt20ApplicationAttributeEb \
      _ZN16QCoreApplication12setAttributeEN2Qt20ApplicationAttributeEb

$o _ZN2QT7QTabBar13setTabToolTipEiRKNS_7QStringE \
      _ZN7QTabBar13setTabToolTipEiRK7QString

$o _ZN2QT23qUnregisterResourceDataEiPKhS1_S1_ \
       _Z23qUnregisterResourceDataiPKhS0_S0_

$o _ZNK2QT10QTableView14verticalHeaderEv \
      _ZNK10QTableView14verticalHeaderEv

$o _ZN2QT5QIconC1ERKS0_ \
   _ZN2QT5QIconC1ERKS0_

$o _ZN2QT11QHeaderView21setStretchLastSectionEb \
         _ZN11QHeaderView21setStretchLastSectionEb

$o _ZN2QT9QSplitterC1ENS_2Qt11OrientationEPNS_7QWidgetE \
      _ZN9QSplitterC1EN2Qt11OrientationEP7QWidget

$o _ZN2QT5QIconC1ERKS0_ \
      _ZN5QIconC1ERKS_

$o _ZN2QT5QFont13setFixedPitchEb \
      _ZN5QFont13setFixedPitchEb

$o _ZNK2QT7QString3argExiiNS_5QCharE \
      _ZNK7QString3argExii5QChar

$o _ZN2QT10QTabWidget13setTabEnabledEib \
      _ZN10QTabWidget13setTabEnabledEib

$o _ZNK2QT9QSplitter5countEv \
      _ZNK9QSplitter5countEv

$o _ZNK2QT7QAction8shortcutEv \
      _ZNK7QAction8shortcutEv

$o _ZN2QT9QSplitterC1EPNS_7QWidgetE \
      _ZN9QSplitterC1EP7QWidget

$o _ZN2QT6QLabel23setTextInteractionFlagsENS_6QFlagsINS_2Qt19TextInteractionFlagEEE \
      _ZN6QLabel23setTextInteractionFlagsE6QFlagsIN2Qt19TextInteractionFlagEE

$o _ZN2QT15QGuiApplication7screensEv \
   _ZN2QT15QGuiApplication7screensEv

$o _ZN2QT15QGuiApplication7screensEv \
      _ZN15QGuiApplication7screensEv

$o _ZN2QT7QWidgetC2EPS0_NS_6QFlagsINS_2Qt10WindowTypeEEE \
      _ZN7QWidgetC2EPS_6QFlagsIN2Qt10WindowTypeEE

$o _ZN2QT8QPainter12drawPolylineEPKNS_6QPointEi \
      _ZN8QPainter12drawPolylineEPK6QPointi

$o _ZN2QT10QByteArray7fromHexERKS0_ \
      _ZN10QByteArray7fromHexERKS_

$o _ZN2QT14QPlainTextEdit9selectAllEv \
      _ZN14QPlainTextEdit9selectAllEv

$o _ZNK2QT7QPixmap4sizeEv \
      _ZNK7QPixmap4sizeEv

$o _ZN2QT7QWidget18setContentsMarginsEiiii \
      _ZN7QWidget18setContentsMarginsEiiii

$o _ZN2QT7QPixmapC1ERKS0_ \
      _ZN7QPixmapC1ERKS_

$o _ZN2QT13QTextDocument11setModifiedEb \
      _ZN13QTextDocument11setModifiedEb

$o _ZNK2QT7QTabBar7tabTextEi \
      _ZNK7QTabBar7tabTextEi

$o _ZN2QT7QWidget4showEv \
      _ZN7QWidget4showEv

$o _ZN2QT7QAction10setToolTipERKNS_7QStringE \
      _ZN7QAction10setToolTipERK7QString

$o _ZN2QT11QHeaderView20setHighlightSectionsEb \
      _ZN11QHeaderView20setHighlightSectionsEb

$o _ZNK2QT7QAction11isCheckableEv \
      _ZNK7QAction11isCheckableEv

$o _ZN2QT9QGroupBoxC1EPNS_7QWidgetE \
      _ZN9QGroupBoxC1EP7QWidget

$o _ZNK2QT7QString5splitENS_5QCharENS_6QFlagsINS_2Qt18SplitBehaviorFlagsEEENS3_15CaseSensitivityE \
      _ZNK7QString5splitE5QChar6QFlagsIN2Qt18SplitBehaviorFlagsEENS2_15CaseSensitivityE

echo $LINENO

$o _ZNK2QT12QTableWidget10currentRowEv \
      _ZNK12QTableWidget10currentRowEv

$o _ZN2QT12QTableWidget11setRowCountEi \
      _ZN12QTableWidget11setRowCountEi

$o _ZNK2QT19QAbstractScrollArea17verticalScrollBarEv \
      _ZNT19QAbstractScrollArea17verticalScrollBarEv

$o _ZNT19QAbstractScrollArea17verticalScrollBarEv \
   _ZNK19QAbstractScrollArea17verticalScrollBarEv

$o _ZN2QT7QWidget9setParentEPS0_ \
      _ZN7QWidget9setParentEPS_

$o _ZN2QT12QApplication6notifyEPNS_7QObjectEPNS_6QEventE \
      _ZN12QApplication6notifyEP7QObjectP6QEvent

$o _ZN2QT7QRegExpD1Ev \
      _ZN7QRegExpD1Ev

$o _ZN2QT16QCoreApplication14applicationPidEv \
      _ZN16QCoreApplication14applicationPidEv

$o _ZN2QT5QDrag4execENS_6QFlagsINS_2Qt10DropActionEEE \
      _ZN5QDrag4execE6QFlagsIN2Qt10DropActionEE

$o _ZN2QT6QLabel7setTextERKNS_7QStringE \
      _ZN6QLabel7setTextERK7QString

$o _ZNK2QT9QFontInfo6italicEv \
      _ZNK9QFontInfo6italicEv

$o _ZNK2QT8QVariant3cmpERKS0_ \
      _ZNK8QVariant3cmpERKS_

$o _ZN2QT7QWidget12removeActionEPNS_7QActionE \
      _ZN7QWidget12removeActionEP7QAction

$o _ZN2QT11QTreeWidget14setColumnCountEi \
      _ZN11QTreeWidget14setColumnCountEi

$o _ZNK2QT7QPixmap19createMaskFromColorERKNS_6QColorENS_2Qt8MaskModeE \
      _ZNK7QPixmap19createMaskFromColorERK6QColorN2Qt8MaskModeE

$o _ZN2QT9QCheckBoxC2ERKNS_7QStringEPNS_7QWidgetE \
      _ZN9QCheckBoxC1ERK7QStringP7QWidget

$o _ZN2QT9QTreeView6expandERKNS_11QModelIndexE \
      _ZN9QTreeView6expandERK11QModelIndex

$o _ZN2QT7QWidget10setPaletteERKNS_8QPaletteE \
      _ZN7QWidget10setPaletteERK8QPalette

$o _ZN2QT7QObjectD2Ev \
      _ZN7QObjectD2Ev

$o _ZN2QT5QDrag10setHotSpotERKNS_6QPointE \
      _ZN5QDrag10setHotSpotERK6QPoint

$o _ZN2QT7QRegionC1EiiiiNS0_10RegionTypeE \
      _ZN7QRegionC1EiiiiNS_10RegionTypeE

$o _ZN2QT9QLineEdit5clearEv \
      _ZN9QLineEdit5clearEv

$o _ZN2QT5QIconC1Ev \
      _ZN5QIconC1Ev

$o _ZN2QT14QPlainTextEdit11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN14QPlainTextEdit11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT11QListWidget10insertItemEiRKNS_7QStringE \
      _ZN11QListWidget10insertItemEiRK7QString

$o _ZN2QT9QListData7reallocEi \
      _ZN9QListData7reallocEi

$o _ZNK2QT8QPainter3penEv \
      _ZNK8QPainter3penEv

$o _ZN2QT12QApplication11focusWidgetEv \
      _ZN12QApplication11focusWidgetEv

$o _ZN2QT11QMetaObject8activateEPNS_7QObjectEPKS0_iPPv \
      _ZN11QMetaObject8activateEP7QObjectPKS_iPPv

$o _ZN2QT7QWidget13setFocusProxyEPS0_ \
      _ZN7QWidget13setFocusProxyEPS_

$o _ZN2QT7QAction7setDataERKNS_8QVariantE \
      _ZN7QAction7setDataERK8QVariant

$o _ZN2QT8QPaletteC1Ev \
      _ZN8QPaletteC1Ev

$o _ZN2QT13QElapsedTimer7restartEv \
      _ZN13QElapsedTimer7restartEv

echo $LINENO

$o _ZNK2QT12QTableWidget3rowEPKNS_16QTableWidgetItemE \
      _ZNK12QTableWidget3rowEPK16QTableWidgetItem

$o _ZN2QT24QAccessibleTextInterfaceD2Ev \
      _ZN24QAccessibleTextInterfaceD2Ev

$o _ZN2QT6QEventC2ERKS0_ \
      _ZN6QEventC2ERKS_

$o _ZN2QT10QByteArray5clearEv \
      _ZN10QByteArray5clearEv

$o _ZN2QT17QAbstractItemView4editERKNS_11QModelIndexE \
   _ZN17QAbstractItemView4editERK11QModelIndex

$o _ZN2QT11QFormLayoutC1EPNS_7QWidgetE \
      _ZN11QFormLayoutC1EP7QWidget

$o _ZN2QT9QGroupBox8setTitleERKNS_7QStringE \
      _ZN9QGroupBox8setTitleERK7QString

$o _ZN2QT11QTextFormatC2ERKS0_ \
      _ZN11QTextFormatC2ERKS_

$o _ZNK2QT5QMenu5titleEv \
      _ZNK5QMenu5titleEv

$o _ZN2QT14QItemSelectionC1ERKNS_11QModelIndexES3_ \
      _ZN14QItemSelectionC1ERK11QModelIndexS2_

$o _ZN2QT11QFontDialogD2Ev \
      _ZN11QFontDialogD2Ev

$o _ZN2QT11QTextStreamC1EPNS_9QIODeviceE \
      _ZN11QTextStreamC1EP9QIODevice

$o _ZN2QT15QGuiApplication17keyboardModifiersEv \
      _ZN15QGuiApplication17keyboardModifiersEv

$o _ZN2QT18QAbstractItemModel11dataChangedERKNS_11QModelIndexES3_RKNS_7QVectorIiEE \
      _ZN18QAbstractItemModel11dataChangedERK11QModelIndexS2_RK7QVectorIiE

$o _ZN2QT11QTreeWidget14setCurrentItemEPNS_15QTreeWidgetItemE \
      _ZN11QTreeWidget14setCurrentItemEP15QTreeWidgetItem

$o _ZNK2QT7QAction4fontEv \
      _ZNK7QAction4fontEv

$o _ZN2QT11QHeaderView21setDefaultSectionSizeEi \
      _ZN11QHeaderView21setDefaultSectionSizeEi

$o _ZNK2QT9QFontInfo9styleNameEv \
      _ZNK9QFontInfo9styleNameEv

$o _ZN2QT7QWidget8setStyleEPNS_6QStyleE \
      _ZN7QWidget8setStyleEP6QStyle

$o _ZN2QT9QComboBox10removeItemEi \
      _ZN9QComboBox10removeItemEi

$o _ZNK2QT9QFontInfo9pointSizeEv \
      _ZNK9QFontInfo9pointSizeEv

$o _ZN2QT15QAbstractSlider11setPageStepEi \
      _ZN15QAbstractSlider11setPageStepEi

$o _ZN2QT10QTransformC1Ev \
      _ZN10QTransformC1Ev

$o _ZNK2QT7QWidget14ensurePolishedEv \
      _ZNK2QT7QWidget14ensurePolishedEv

$o _ZNK2QT7QWidget14ensurePolishedEv \
      _ZNK7QWidget14ensurePolishedEv

$o _ZN2QT9QHashData11free_helperEPFvPNS0_4NodeEE \
      _ZN9QHashData11free_helperEPFvPNS_4NodeEE

$o _ZN2QT4QPen8setWidthEi \
      _ZN4QPen8setWidthEi

$o _ZNK2QT12QMapNodeBase8nextNodeEv \
      _ZNK12QMapNodeBase8nextNodeEv

$o _ZN2QT20QStyleOptionMenuItemC1Ev \
      _ZN20QStyleOptionMenuItemC1Ev

$o _ZN2QT6QFrame12setLineWidthEi \
      _ZN6QFrame12setLineWidthEi

$o _ZN2QT9QCheckBoxC1EPNS_7QWidgetE \
      _ZN9QCheckBoxC1EP7QWidget

$o _ZN2QT9QCheckBoxD2Ev \
      _ZN9QCheckBoxD2Ev

$o _ZN2QT10QTableView11setShowGridEb \
      _ZN10QTableView11setShowGridEb

echo $LINENO

$o _ZN2QT5QChar14isSpace_helperEj \
      _ZN5QChar14isSpace_helperEj

$o _ZN2QT9QListData7disposeEPNS0_4DataE \
      _ZN9QListData7disposeEPNS_4DataE

$o _ZN2QT7QObject18installEventFilterEPS0_ \
      _ZN7QObject18installEventFilterEPS_

$o _ZNK2QT7QWidget11windowTitleEv \
      _ZNK7QWidget11windowTitleEv

$o _ZNK2QT16QDialogButtonBox6buttonENS0_14StandardButtonE \
      _ZNK16QDialogButtonBox6buttonENS_14StandardButtonE

$o _ZN2QT9QLineEdit7setTextERKNS_7QStringE \
      _ZN9QLineEdit7setTextERK7QString

$o _ZN2QT18QAbstractItemModel18beginInsertColumnsERKNS_11QModelIndexEii \
      _ZN18QAbstractItemModel18beginInsertColumnsERK11QModelIndexii

$o _ZN2QT10QCompleterC1EPNS_7QObjectE \
      _ZN10QCompleterC1EP7QObject

$o _ZNK2QT8QVariant5toIntEPb \
      _ZNK8QVariant5toIntEPb

$o _ZNK2QT8QPalette5brushENS0_10ColorGroupENS0_9ColorRoleE \
      _ZNK8QPalette5brushENS_10ColorGroupENS_9ColorRoleE

$o _ZNK2QT8QPalette5brushENS0_10ColorGroupENS0_9ColorRoleE \
      _ZNK8QPalette5brushENS_10ColorGroupENS_9ColorRoleE

$o _ZNK2QT12QTableWidget8rowCountEv \
      _ZNK12QTableWidget8rowCountEv

$o _ZNK2QT7QString5countENS_5QCharENS_2Qt15CaseSensitivityE \
      _ZNK7QString5countE5QCharN2Qt15CaseSensitivityE

$o _ZN2QT11QVBoxLayoutC1Ev \
      _ZN11QVBoxLayoutC1Ev

$o _ZN2QT9QComboBox15setInsertPolicyENS0_12InsertPolicyE \
      _ZN9QComboBox15setInsertPolicyENS_12InsertPolicyE

$o _ZN2QT6QColor10colorNamesEv \
      _ZN6QColor10colorNamesEv

$o _ZN2QT6QTimer4stopEv \
      _ZN6QTimer4stopEv

$o _ZN2QT7QString6removeENS_5QCharENS_2Qt15CaseSensitivityE \
      _ZN7QString6removeE5QCharN2Qt15CaseSensitivityE

$o _ZNK2QT7QWidget7paletteEv \
      _ZNK7QWidget7paletteEv

$o _ZN2QT11QDockWidget15setAllowedAreasENS_6QFlagsINS_2Qt14DockWidgetAreaEEE \
      _ZN11QDockWidget15setAllowedAreasE6QFlagsIN2Qt14DockWidgetAreaEE

$o _ZNK2QT9QComboBox10isEditableEv \
      _ZNK9QComboBox10isEditableEv

$o _ZN2QT16QCoreApplication19setOrganizationNameERKNS_7QStringE \
      _ZN16QCoreApplication19setOrganizationNameERK7QString

$o _ZN2QT11QListWidget11insertItemsEiRKNS_11QStringListE \
      _ZN11QListWidget11insertItemsEiRK11QStringList

$o _ZNK2QT11QHeaderView14logicalIndexAtEi \
      _ZNK11QHeaderView14logicalIndexAtEi

$o _ZNK2QT11QTreeWidget17topLevelItemCountEv \
      _ZNK11QTreeWidget17topLevelItemCountEv

$o _ZN2QT17QAbstractItemView15setCurrentIndexERKNS_11QModelIndexE \
      _ZN17QAbstractItemView15setCurrentIndexERK11QModelIndex

$o _ZN2QT21QPersistentModelIndexC1ERKS0_ \
      _ZN21QPersistentModelIndexC1ERKS_

$o _ZN2QT11QHeaderView21setMinimumSectionSizeEi \
      _ZN11QHeaderView21setMinimumSectionSizeEi

$o _ZN2QT7QObject17removeEventFilterEPS0_ \
      _ZN7QObject17removeEventFilterEPS_

$o _ZN2QT8QPainter8fillRectERKNS_5QRectERKNS_6QBrushE \
      _ZN8QPainter8fillRectERK5QRectRK6QBrush

$o _ZN2QT11QGridLayout7addItemEPNS_11QLayoutItemEiiiiNS_6QFlagsINS_2Qt13AlignmentFlagEEE \
      _ZN11QGridLayout7addItemEP11QLayoutItemiiii6QFlagsIN2Qt13AlignmentFlagEE

$o _ZNK2QT15QAbstractButton9isCheckedEv \
      _ZNK15QAbstractButton9isCheckedEv

echo $LINENO

$o _ZN2QT12QTableWidget11qt_metacastEPKc \
      _ZN12QTableWidget11qt_metacastEPKc

$o _ZN2QT7QLayout18setContentsMarginsEiiii \
      _ZN7QLayout18setContentsMarginsEiiii

$o _ZN2QT11QScrollArea9setWidgetEPNS_7QWidgetE \
      _ZN11QScrollArea9setWidgetEP7QWidget

$o _ZN2QT9QTextEdit16setOverwriteModeEb \
      _ZN9QTextEdit16setOverwriteModeEb

$o _ZNK2QT7QWidget12saveGeometryEv \
      _ZNK7QWidget12saveGeometryEv

$o _ZN2QT7QWidget12setFixedSizeEii \
      _ZN7QWidget12setFixedSizeEii

$o _ZN2QT7QAction11setShortcutERKNS_12QKeySequenceE \
      _ZN7QAction11setShortcutERK12QKeySequence

$o _ZN2QT7QAction11setMenuRoleENS0_8MenuRoleE \
      _ZN7QAction11setMenuRoleENS_8MenuRoleE

$o _ZN2QT9QSplitter7refreshEv \
      _ZN9QSplitter7refreshEv

$o _ZNK2QT11QHeaderView11sectionSizeEi \
      _ZNK11QHeaderView11sectionSizeEi

$o _ZN2QT12QStyleOption4initEPKNS_7QWidgetE \
      _ZN12QStyleOption4initEPK7QWidget

$o _ZN2QT8QVariantC1ERKNS_5QRectE \
      _ZN8QVariantC1ERK5QRect

$o _ZNK2QT7QWidget8hasFocusEv \
      _ZNK7QWidget8hasFocusEv

$o _ZNK2QT5QFont5styleEv \
      _ZNK5QFont5styleEv

$o _ZNK2QT8QPrinter7isValidEv \
      _ZNK8QPrinter7isValidEv

$o _ZN2QT11QHBoxLayoutC1Ev \
      _ZN11QHBoxLayoutC1Ev

$o _ZN2QT12QButtonGroupC1EPNS_7QObjectE \
      _ZN12QButtonGroupC1EP7QObject

$o _ZN2QT6QBrushC1ERKNS_9QGradientE \
      _ZN6QBrushC1ERK9QGradient

$o _ZN2QT6QBrushC1ERKNS_9QGradientE \
      _ZN6QBrushC1ERK9QGradient

$o _ZN2QT7QWidget5closeEv \
      _ZN7QWidget5closeEv

$o _ZN2QT12QPixmapCache4findERKNS_7QStringEPNS_7QPixmapE \
      _ZN12QPixmapCache4findERK7QStringP7QPixmap

$o _ZNK2QT8QPainter5brushEv \
      _ZNK8QPainter5brushEv

$o _ZN2QT11QScrollAreaC1EPNS_7QWidgetE \
      _ZN11QScrollAreaC1EP7QWidget

$o _ZN2QT7QWidget14setWindowFlagsENS_6QFlagsINS_2Qt10WindowTypeEEE \
      _ZN7QWidget14setWindowFlagsE6QFlagsIN2Qt10WindowTypeEE

$o _ZN2QT4QPen8setColorERKNS_6QColorE \
      _ZN4QPen8setColorERK6QColor

$o _ZN2QTlsERNS_11QDataStreamERKNS_7QStringE \
           _ZrsR11QDataStreamR7QString

$o _ZN2QT6QColor13setNamedColorERKNS_7QStringE \
      _ZN6QColor13setNamedColorERK7QString

$o _ZN2QT14QItemSelection6selectERKNS_11QModelIndexES3_ \
      _ZN14QItemSelection6selectERK11QModelIndexS2_

$o _ZN2QT11QMessageBox11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN11QMessageBox11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZNK2QT7QString10startsWithENS_5QCharENS_2Qt15CaseSensitivityE \
      _ZNK7QString10startsWithE5QCharN2Qt15CaseSensitivityE

$o _ZN2QT8QPainter8drawTextERKNS_6QRectFERKNS_7QStringERKNS_11QTextOptionE \
      _ZN8QPainter8drawTextERK6QRectFRK7QStringRK11QTextOption

$o _ZN2QT7QString7replaceEiiRKS0_ \
      _ZN7QString7replaceEiiRKS_

$o _ZN2QT7QString8asprintfEPKcz \
      _ZN7QString8asprintfEPKcz

echo $LINENO

$o _ZN2QT12QFontMetricsC1ERKNS_5QFontE \
      _ZN12QFontMetricsC1ERK5QFont

$o _ZN2QT20qt_qFindChild_helperEPKNS_7QObjectERKNS_7QStringERKNS_11QMetaObjectENS_6QFlagsINS_2Qt15FindChildOptionEEE \
       _Z20qt_qFindChild_helperPK7QObjectRK7QStringRK11QMetaObject6QFlagsIN2Qt15FindChildOptionEE

$o _ZN2QT12QButtonGroup12setExclusiveEb \
      _ZN12QButtonGroup12setExclusiveEb

$o _ZN2QT11QWheelEventC1ENS_7QPointFES1_NS_6QPointES2_NS_6QFlagsINS_2Qt11MouseButtonEEENS3_INS4_16KeyboardModifierEEENS4_11ScrollPhaseEbNS4_16MouseEventSourceE \
      _ZN11QWheelEventC1E7QPointFS0_6QPointS1_6QFlagsIN2Qt11MouseButtonEES2_INS3_16KeyboardModifierEENS3_11ScrollPhaseEbNS3_16MouseEventSourceE

$o _ZN2QT8QPainter9drawLinesEPKNS_5QLineEi \
      _ZN8QPainter9drawLinesEPK5QLinei

$o _ZN2QT10QStatusBarC1EPNS_7QWidgetE \
      _ZN10QStatusBarC1EP7QWidget

$o _ZNK2QT6QColor3rgbEv \
      _ZNK6QColor3rgbEv

$o _ZN2QT11QGridLayoutC1EPNS_7QWidgetE \
      _ZN11QGridLayoutC1EP7QWidget

$o _ZNK2QT15QAbstractSlider7maximumEv \
      _ZNK15QAbstractSlider7maximumEv

$o _ZN2QT11QMainWindowD2Ev \
      _ZN11QMainWindowD2Ev

$o _ZNK2QT16QDialogButtonBox7buttonsEv \
      _ZNK16QDialogButtonBox7buttonsEv

$o _ZN2QT12QStyleOptionC1Eii \
      _ZN12QStyleOptionC1Eii

$o _ZNK2QT8QVariant8userTypeEv \
      _ZNK8QVariant8userTypeEv

$o _ZN2QT7QPixmapC1ERKNS_5QSizeE \
      _ZN7QPixmapC1ERK5QSize

$o _ZN2QT7QStringC1EiNS_5QCharE \
      _ZN7QStringC1Ei5QChar

$o _ZN2QT14QPlainTextEditC2EPNS_7QWidgetE \
      _ZN14QPlainTextEditC1EP7QWidget

$o _ZN2QT10QTableView11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN10QTableView11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT9QHashData8nextNodeEPNS0_4NodeE \
      _ZN9QHashData8nextNodeEPNS_4NodeE

$o _ZN2QT7QTabBar10setTabIconEiRKNS_5QIconE \
      _ZN7QTabBar10setTabIconEiRK5QIcon

$o _ZN2QT11QFontDialog14setCurrentFontERKNS_5QFontE \
      _ZN11QFontDialog14setCurrentFontERK5QFont

$o _ZN2QT16QDialogButtonBox9addButtonERKNS_7QStringENS0_10ButtonRoleE \
      _ZN16QDialogButtonBox9addButtonERK7QStringNS_10ButtonRoleE

$o _ZN2QT5QMenu5eventEPNS_6QEventE \
      _ZN5QMenu5eventEP6QEvent

$o _ZN2QT9QComboBox24setMinimumContentsLengthEi \
      _ZN9QComboBox24setMinimumContentsLengthEi

$o _ZN2QT11QDockWidget17setTitleBarWidgetEPNS_7QWidgetE \
      _ZN11QDockWidget17setTitleBarWidgetEP7QWidget

$o _ZN2QT9QListData5eraseEPPv \
      _ZN9QListData5eraseEPPv

$o _ZN2QT10QBoxLayout13insertStretchEii \
      _ZN10QBoxLayout13insertStretchEii

$o _ZN2QT11QTextOptionD1Ev \
      _ZN11QTextOptionD1Ev

$o _ZN2QT6QColor9setAlphaFEd \
      _ZN6QColor9setAlphaFEd

$o _ZNK2QT9QComboBox8itemTextEi \
      _ZNK9QComboBox8itemTextEi

$o _ZNK2QT12QFontMetrics4sizeEiRKNS_7QStringEiPi \
      _ZNK12QFontMetrics4sizeEiRK7QStringiPi

$o _ZNK2QT14QPlainTextEdit13contentOffsetEv \
      _ZNK14QPlainTextEdit13contentOffsetEv

$o _ZN2QT12QPixmapCache6insertERKNS_7QStringERKNS_7QPixmapE \
      _ZN12QPixmapCache6insertERK7QStringRK7QPixmap

$o _ZNK2QT14QStackedWidget7indexOfEPNS_7QWidgetE \
      _ZNK14QStackedWidget7indexOfEP7QWidget

echo $LINENO

$o _ZN2QT7QRegionD1Ev \
      _ZN7QRegionD1Ev

$o _ZNK2QT9QMimeData7hasUrlsEv \
      _ZNK9QMimeData7hasUrlsEv

$o _ZNK2QT7QWidget12isAncestorOfEPKS0_ \
      _ZNK7QWidget12isAncestorOfEPKS_

$o _ZNK2QT7QWidget10sizePolicyEv \
      _ZNK7QWidget10sizePolicyEv

$o _ZN2QT5QFontC1ERKS0_ \
      _ZN5QFontC1ERKS_

$o _ZN2QT5QFont12setStyleNameERKNS_7QStringE \
      _ZN5QFont12setStyleNameERK7QString

$o _ZN2QT7QWidgetD2Ev \
      _ZN7QWidgetD2Ev

$o _ZNK2QT13QFontMetricsF6ascentEv \
      _ZNK13QFontMetricsF6ascentEv

$o _ZN2QT15QTextCharFormatC1Ev \
      _ZN15QTextCharFormatC1Ev

$o _ZN2QT11QTreeWidget11qt_metacastEPKc \
      _ZN11QTreeWidget11qt_metacastEPKc

$o _ZN2QTlsERNS_11QDataStreamERKNS_5QRectE \
           _ZrsR11QDataStreamR5QRect

$o _ZN2QT11QHeaderView13resizeSectionEii \
      _ZN11QHeaderView13resizeSectionEii

$o _ZN2QT5QMenu8setTitleERKNS_7QStringE \
      _ZN5QMenu8setTitleERK7QString

$o _ZNK2QT14QPlainTextEdit10isReadOnlyEv \
      _ZNK14QPlainTextEdit10isReadOnlyEv

$o _ZNK2QT5QMenu10menuActionEv \
      _ZNK5QMenu10menuActionEv

$o _ZN2QT11QPushButtonC1EPNS_7QWidgetE \
      _ZN11QPushButtonC1EP7QWidget

$o _ZNK2QT7QWidget5winIdEv \
      _ZNK7QWidget5winIdEv

$o _ZNK2QT14QMessageLogger5debugEv \
      _ZNK14QMessageLogger5debugEv

$o _ZNK2QT12QTableWidget20horizontalHeaderItemEi \
      _ZNK12QTableWidget20horizontalHeaderItemEi

$o _ZN2QT7QString14toUpper_helperERS0_ \
      _ZN7QString14toUpper_helperERS_

$o _ZN2QT11QHeaderView21setSortIndicatorShownEb \
      _ZN11QHeaderView21setSortIndicatorShownEb

$o _ZNK2QT14QPlainTextEdit10blockCountEv \
      _ZNK14QPlainTextEdit10blockCountEv

$o _ZN2QT11QMainWindow12restoreStateERKNS_10QByteArrayEi \
      _ZN11QMainWindow12restoreStateERK10QByteArrayi

$o _ZNK2QT9QTreeView10indexBelowERKNS_11QModelIndexE \
      _ZNK9QTreeView10indexBelowERK11QModelIndex

$o _ZN2QT10QScrollBarC2EPNS_7QWidgetE \
      _ZN10QScrollBarC1EP7QWidget

$o _ZNK2QT14QStackedWidget13currentWidgetEv \
      _ZNK14QStackedWidget13currentWidgetEv

$o _ZN2QT4QUrlD1Ev \
      _ZN4QUrlD1Ev

$o _ZN2QT9QLineEdit12setAlignmentENS_6QFlagsINS_2Qt13AlignmentFlagEEE \
      _ZN9QLineEdit12setAlignmentE6QFlagsIN2Qt13AlignmentFlagEE

$o _ZN2QT7QWidget10setToolTipERKNS_7QStringE \
      _ZN7QWidget10setToolTipERK7QString

$o _ZNK2QT9QComboBox8lineEditEv \
      _ZNK9QComboBox8lineEditEv

$o _ZNK2QT12QTableWidget13selectedItemsEv \
      _ZNK12QTableWidget13selectedItemsEv

$o _ZN2QT11QTextCursor18removeSelectedTextEv \
      _ZN11QTextCursor18removeSelectedTextEv

echo $LINENO

$o _ZN2QT6QColor8setAlphaEi \
      _ZN6QColor8setAlphaEi

$o _ZN2QT12QRadioButtonC1EPNS_7QWidgetE \
      _ZN12QRadioButtonC1EP7QWidget

$o _ZN2QT11QProxyStyleC2EPNS_6QStyleE \
      _ZN11QProxyStyleC2EP6QStyle

$o _ZN2QT8QPainter10drawPixmapERKNS_7QPointFERKNS_7QPixmapE \
      _ZN8QPainter10drawPixmapERK7QPointFRK7QPixmap

$o _ZN2QT8QPainter10drawPixmapERKNS_7QPointFERKNS_7QPixmapE \
      _ZN8QPainter10drawPixmapERK7QPointFRK7QPixmap

$o _ZNK2QT7QWidget10windowIconEv \
      _ZNK7QWidget10windowIconEv

$o _ZN2QT7QWidget14updateGeometryEv \
      _ZN7QWidget14updateGeometryEv

$o _ZN2QT18QAbstractItemModel11qt_metacastEPKc \
      _ZN18QAbstractItemModel11qt_metacastEPKc

$o _ZNK2QT7QRegExp13matchedLengthEv \
      _ZNK7QRegExp13matchedLengthEv

$o _ZN2QT11QDockWidget11qt_metacastEPKc \
      _ZN11QDockWidget11qt_metacastEPKc

$o _ZNK2QT9QFileInfo12absolutePathEv \
      _ZNK9QFileInfo12absolutePathEv

$o _ZN2QT11QMainWindow13removeToolBarEPNS_8QToolBarE \
      _ZN11QMainWindow13removeToolBarEP8QToolBar

$o _ZN2QT10QCompleter8setModelEPNS_18QAbstractItemModelE \
      _ZN10QCompleter8setModelEP18QAbstractItemModel

$o _ZN2QT6QImageaSERKS0_ \
      _ZN6QImageaSERKS_

$o _ZN2QT9QLineEdit12setCompleterEPNS_10QCompleterE \
      _ZN9QLineEdit12setCompleterEP10QCompleter

$o _ZN2QT7QWidget12setAttributeENS_2Qt15WidgetAttributeEb \
      _ZN7QWidget12setAttributeEN2Qt15WidgetAttributeEb

$o _ZN2QT11QPushButtonC1ERKNS_5QIconERKNS_7QStringEPNS_7QWidgetE \
      _ZN11QPushButtonC2ERK5QIconRK7QStringP7QWidget

$o _ZN2QT11QMetaObject10ConnectionC1ERKS1_ \
      _ZN11QMetaObject10ConnectionC1ERKS0_

$o _ZN2QT9QMimeDataC1Ev \
      _ZN9QMimeDataC1Ev

$o _ZN2QT6QColoraSERKS0_ \
      _ZN6QColoraSERKS_

$o _ZN2QT11QTextLayout9endLayoutEv \
      _ZN11QTextLayout9endLayoutEv

$o _ZNK2QT5QIcon14availableSizesENS0_4ModeENS0_5StateE \
      _ZNK5QIcon14availableSizesENS_4ModeENS_5StateE

$o _ZN2QT7QTabBar15mousePressEventEPNS_11QMouseEventE \
      _ZN7QTabBar15mousePressEventEP11QMouseEvent

$o _ZN2QT7QTabBar15setCurrentIndexEi \
      _ZN7QTabBar15setCurrentIndexEi

$o _ZN2QT7QTabBar12setElideModeENS_2Qt13TextElideModeE \
      _ZN7QTabBar12setElideModeEN2Qt13TextElideModeE

$o _ZN2QT19QStyleOptionToolBarC1Ev \
      _ZN19QStyleOptionToolBarC1Ev

$o _ZNK2QT11QMainWindow9saveStateEi \
      _ZNK11QMainWindow9saveStateEi

$o _ZN2QT9QSplitter15setOpaqueResizeEb \
      _ZN9QSplitter15setOpaqueResizeEb

$o _ZNK2QT7QAction11isSeparatorEv \
      _ZNK7QAction11isSeparatorEv

$o _ZNK2QT7QAction4menuEv \
      _ZNK7QAction4menuEv

$o _ZN2QT8QSpinBox8setValueEi \
      _ZN8QSpinBox8setValueEi

$o _ZN2QT7QActionD2Ev \
      _ZN7QActionD2Ev

$o _ZN2QT9QLineEdit11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN9QLineEdit11qt_metacallEN11QMetaObject4CallEiPPv

echo $LINENO

$o _ZN2QT16QDialogButtonBox9addButtonEPNS_15QAbstractButtonENS0_10ButtonRoleE \
      _ZN16QDialogButtonBox9addButtonEP15QAbstractButtonNS_10ButtonRoleE

$o _ZN2QT7QPixmap7setMaskERKNS_7QBitmapE \
      _ZN7QPixmap7setMaskERK7QBitmap

$o _ZN2QT5QFont12setStyleHintENS0_9StyleHintENS0_13StyleStrategyE \
      _ZN5QFont12setStyleHintENS_9StyleHintENS_13StyleStrategyE

$o _ZN2QT14QStackedWidget16setCurrentWidgetEPNS_7QWidgetE \
      _ZN14QStackedWidget16setCurrentWidgetEP7QWidget

$o _ZN2QT6QEventC2ENS0_4TypeE \
      _ZN6QEventC2ENS_4TypeE

$o _ZN2QT7QObject10disconnectERKNS_11QMetaObject10ConnectionE \
      _ZN7QObject10disconnectERKN11QMetaObject10ConnectionE

$o _ZN2QT9QSplitter5eventEPNS_6QEventE \
      _ZN9QSplitter5eventEP6QEvent

$o _ZN2QT11QTreeWidget15setHeaderLabelsERKNS_11QStringListE \
      _ZN11QTreeWidget15setHeaderLabelsERK11QStringList

$o _ZNK2QT6QColoreqERKS0_ \
      _ZNK6QColoreqERKS_

$o _ZNK2QT10QTextBlock9isVisibleEv \
      _ZNK10QTextBlock9isVisibleEv

$o _ZNK2QT9QKeyEvent9modifiersEv \
      _ZNK9QKeyEvent9modifiersEv

$o _ZN2QT5QFontD1Ev \
      _ZN5QFontD1Ev

$o _ZNK2QT7QString3argERKS0_iNS_5QCharE \
      _ZNK7QString3argERKS_i5QChar

$o _ZN2QT12QPrintDialogD1Ev \
      _ZN12QPrintDialogD1Ev

$o _ZN2QT8QVariantC1Ei \
      _ZN8QVariantC1Ei

$o _ZNK2QT15QAbstractSlider14sliderPositionEv \
      _ZNK15QAbstractSlider14sliderPositionEv

$o _ZNK2QT19QAbstractScrollArea15viewportMarginsEv \
      _ZNK19QAbstractScrollArea15viewportMarginsEv

$o _ZN2QT7QString6numberEdci \
      _ZN7QString6numberEdci

$o _ZN2QT19QAbstractScrollArea18setViewportMarginsERKNS_8QMarginsE \
      _ZN19QAbstractScrollArea18setViewportMarginsERK8QMargins

$o _ZN2QT12QMapDataBase20freeNodeAndRebalanceEPNS_12QMapNodeBaseE \
      _ZN12QMapDataBase20freeNodeAndRebalanceEP12QMapNodeBase

$o _ZNK2QT11QHeaderView18defaultSectionSizeEv \
      _ZNK11QHeaderView18defaultSectionSizeEv

$o _ZNK2QT9QFontInfo9styleHintEv \
      _ZNK9QFontInfo9styleHintEv

$o _ZN2QT14QStackedWidget12removeWidgetEPNS_7QWidgetE \
      _ZN14QStackedWidget12removeWidgetEP7QWidget

$o _ZN2QT8QPainterC1EPNS_12QPaintDeviceE \
      _ZN8QPainterC1EP12QPaintDevice

$o _ZNK2QT7QScreen17availableGeometryEv \
      _ZNK7QScreen17availableGeometryEv

$o _ZN2QT15QGuiApplication17setOverrideCursorERKNS_7QCursorE \
      _ZN15QGuiApplication17setOverrideCursorERK7QCursor

$o _ZN2QT9QListData6insertEi \
      _ZN9QListData6insertEi

$o _ZNK2QT12QTableWidget11columnCountEv \
      _ZNK12QTableWidget11columnCountEv

$o _ZN2QT15QAbstractButton7setTextERKNS_7QStringE \
      _ZN2QT15QAbstractButton7setTextERKNS_7QStringE

$o _ZN2QT15QAbstractButton7setTextERKNS_7QStringE \
      _ZN15QAbstractButton7setTextERK7QString

$o _ZN2QT9QLineEdit12setMaxLengthEi \
      _ZN9QLineEdit12setMaxLengthEi

$o _ZN2QT11QTreeWidget5clearEv \
      _ZN11QTreeWidget5clearEv

$o _ZNK2QT12QKeySequence5countEv \
      _ZNK12QKeySequence5countEv

echo $LINENO

$o _ZN2QT5QIconD1Ev \
      _ZN5QIconD1Ev

$o _ZN2QT11QFileDialog20getExistingDirectoryEPNS_7QWidgetERKNS_7QStringES5_NS_6QFlagsINS0_6OptionEEE \
      _ZN11QFileDialog20getExistingDirectoryEP7QWidgetRK7QStringS4_6QFlagsINS_6OptionEE

$o _ZN2QT17QAbstractItemView23setHorizontalScrollModeENS0_10ScrollModeE \
      _ZN17QAbstractItemView23setHorizontalScrollModeENS_10ScrollModeE

$o _ZNK2QT7QWidget14backgroundRoleEv \
      _ZNK2QT7QWidget14backgroundRoleEv

$o _ZNK2QT7QWidget14backgroundRoleEv \
      _ZNK7QWidget14backgroundRoleEv

$o _ZN2QT15QAbstractButton10setCheckedEb \
      _ZN15QAbstractButton10setCheckedEb

$o _ZN2QT9QFileInfoD1Ev \
      _ZN9QFileInfoD1Ev

$o _ZN2QT19QAbstractScrollArea20setVerticalScrollBarEPNS_10QScrollBarE \
      _ZN19QAbstractScrollArea20setVerticalScrollBarEP10QScrollBar

$o _ZNK2QT11QHeaderView20isSortIndicatorShownEv \
      _ZNK11QHeaderView20isSortIndicatorShownEv

$o _ZNK2QT6QColor4blueEv \
      _ZNK6QColor4blueEv

$o _ZNK2QT7QAction9isEnabledEv \
      _ZNK2QT7QAction9isEnabledEv

$o _ZNK2QT7QAction9isEnabledEv \
      _ZNK7QAction9isEnabledEv

$o _ZNK2QT11QPanGesture5deltaEv \
      _ZNK11QPanGesture5deltaEv

$o _ZN2QT19QAbstractScrollArea26setVerticalScrollBarPolicyENS_2Qt15ScrollBarPolicyE \
      _ZN19QAbstractScrollArea26setVerticalScrollBarPolicyEN2Qt15ScrollBarPolicyE

$o _ZNK2QT9QTreeView6headerEv \
      _ZNK9QTreeView6headerEv

$o _ZN2QT9QListData11detach_growEPii \
      _ZN9QListData11detach_growEPii

$o _ZNK2QT7QTabBar5countEv \
      _ZNK7QTabBar5countEv

$o _ZN2QT4QDirD1Ev \
      _ZN4QDirD1Ev

$o _ZN2QT7QWidget14setFixedHeightEi \
      _ZN7QWidget14setFixedHeightEi

$o _ZN2QT9QLineEdit25createStandardContextMenuEv \
      _ZN9QLineEdit25createStandardContextMenuEv

$o _ZNK2QT9QTextLine6ascentEv \
      _ZNK9QTextLine6ascentEv

$o _ZNK2QT11QDataStream5atEndEv \
      _ZNK11QDataStream5atEndEv

$o _ZN2QT18QSyntaxHighlighter11setDocumentEPNS_13QTextDocumentE \
      _ZN18QSyntaxHighlighter11setDocumentEP13QTextDocument

$o _ZN2QT4QPen11setCapStyleENS_2Qt11PenCapStyleE \
      _ZN4QPen11setCapStyleEN2Qt11PenCapStyleE

$o _ZN2QT10QTransform5scaleEdd \
      _ZN10QTransform5scaleEdd

$o _ZN2QT15QLinearGradientD1Ev \
      _ZN15QLinearGradientD1Ev

$o _ZN2QT12QKeySequence8mnemonicERKNS_7QStringE \
      _ZN12QKeySequence8mnemonicERK7QString

$o _ZN2QT11QHeaderView16setSortIndicatorEiNS_2Qt9SortOrderE \
      _ZN11QHeaderView16setSortIndicatorEiN2Qt9SortOrderE

$o _ZN2QT10QTableViewC2EPNS_7QWidgetE \
      _ZN10QTableViewC2EP7QWidget

$o _ZN2QT18QAbstractItemModelD2Ev \
      _ZN18QAbstractItemModelD2Ev

$o _ZN2QT7QString6appendERKS0_ \
      _ZN7QString6appendERKS_

$o _ZNK2QT21QTextDocumentFragment11toPlainTextEv \
      _ZNK21QTextDocumentFragment11toPlainTextEv

echo $LINENO

$o _ZNK2QT7QPixmap14scaledToHeightEiNS_2Qt18TransformationModeE \
      _ZNK7QPixmap14scaledToHeightEiN2Qt18TransformationModeE

$o _ZN2QT8QPainter8drawTextERKNS_5QRectEiRKNS_7QStringEPS1_ \
      _ZN8QPainter8drawTextERK5QRectiRK7QStringPS0_

$o _ZNK2QT8QVariant12toStringListEv \
      _ZNK8QVariant12toStringListEv

$o _ZNK2QT19QAbstractScrollArea19horizontalScrollBarEv \
      _ZNK19QAbstractScrollArea19horizontalScrollBarEv

$o _ZN2QT16QCoreApplication9postEventEPNS_7QObjectEPNS_6QEventEi \
      _ZN16QCoreApplication9postEventEP7QObjectP6QEventi

$o _ZN2QT7QAction7setMenuEPNS_5QMenuE \
      _ZN7QAction7setMenuEP5QMenu

$o _ZN2QT12QApplication15closeAllWindowsEv \
      _ZN12QApplication15closeAllWindowsEv

$o _ZN2QT18QSyntaxHighlighter11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN18QSyntaxHighlighter11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT7QLayout12setAlignmentEPNS_7QWidgetENS_6QFlagsINS_2Qt13AlignmentFlagEEE \
      _ZN7QLayout12setAlignmentEP7QWidget6QFlagsIN2Qt13AlignmentFlagEE

$o _ZN2QT11QMessageBoxD2Ev \
      _ZN11QMessageBoxD2Ev

$o _ZNK2QT6QColor4nameEv \
      _ZNK6QColor4nameEv

$o _ZN2QT7QTabBar28setSelectionBehaviorOnRemoveENS0_17SelectionBehaviorE \
      _ZN7QTabBar28setSelectionBehaviorOnRemoveENS_17SelectionBehaviorE

$o _ZN2QT14QPlainTextEdit19ensureCursorVisibleEv \
      _ZN14QPlainTextEdit19ensureCursorVisibleEv

$o _ZN2QT14QPlainTextEdit11qt_metacastEPKc \
      _ZN14QPlainTextEdit11qt_metacastEPKc

$o _ZN2QT8QPainter6setPenERKNS_6QColorE \
      _ZN8QPainter6setPenERK6QColor

$o _ZNK2QT17QAbstractItemView5stateEv \
      _ZNK17QAbstractItemView5stateEv

$o _ZN2QT7QPixmapC1Ev \
      _ZN7QPixmapC1Ev

$o _ZN2QT9QLineEditC1EPNS_7QWidgetE \
      _ZN9QLineEditC1EP7QWidget

$o _ZN2QT6QLabel11qt_metacastEPKc \
      _ZN6QLabel11qt_metacastEPKc

$o _ZNK2QT10QTabWidget7indexOfEPNS_7QWidgetE \
      _ZNK10QTabWidget7indexOfEP7QWidget

$o _ZN2QT10QArrayData10deallocateEPS0_mm \
      _ZN10QArrayData10deallocateEPS_mm

$o _ZNK2QT15QAbstractSlider8pageStepEv \
      _ZNK15QAbstractSlider8pageStepEv

$o _ZNK2QT7QString10startsWithERKS0_NS_2Qt15CaseSensitivityE \
      _ZNK7QString10startsWithERKS_N2Qt15CaseSensitivityE

$o _ZN2QT7QWidget13setSizePolicyENS_11QSizePolicyE \
      _ZN7QWidget13setSizePolicyE11QSizePolicy

$o _ZNK2QT15QAbstractButton8shortcutEv \
      _ZNK15QAbstractButton8shortcutEv

$o _ZN2QT7QTabBar6addTabERKNS_7QStringE \
      _ZN7QTabBar6addTabERK7QString

$o _ZN2QT12QApplication10windowIconEv \
      _ZN12QApplication10windowIconEv

$o _ZN2QT12QStyleOptionD1Ev \
      _ZN12QStyleOptionD1Ev

$o _ZN2QT7QWidget8setFocusENS_2Qt11FocusReasonE \
      _ZN7QWidget8setFocusEN2Qt11FocusReasonE

$o _ZN2QT11QMessageBox14setWindowTitleERKNS_7QStringE \
      _ZN11QMessageBox14setWindowTitleERK7QString

$o _ZN2QT11QFormLayout9setLayoutEiNS0_8ItemRoleEPNS_7QLayoutE \
      _ZN11QFormLayout9setLayoutEiNS_8ItemRoleEP7QLayout

$o _ZN2QT6QBrushD1Ev \
      _ZN6QBrushD1Ev

$o _ZN2QT8QVariantD1Ev \
      _ZN8QVariantD1Ev

echo $LINENO

$o _ZN2QT7QString14trimmed_helperERS0_ \
      _ZN7QString14trimmed_helperERS_

$o _ZN2QT16QCoreApplication4exitEi \
      _ZN16QCoreApplication4exitEi

$o _ZN2QT6QTimer11setIntervalEi \
      _ZN6QTimer11setIntervalEi

$o _ZNK2QT10QByteArray8endsWithEc \
      _ZNK10QByteArray8endsWithEc

$o _ZN2QT8QToolBarC1ERKNS_7QStringEPNS_7QWidgetE \
      _ZN8QToolBarC2ERK7QStringP7QWidget

$o _ZN2QT12QMapDataBase8freeDataEPS0_ \
      _ZN12QMapDataBase8freeDataEPS_

$o _ZNK2QT9QTreeView9rowHeightERKNS_11QModelIndexE \
      _ZNK9QTreeView9rowHeightERK11QModelIndex

$o _ZN2QT5QFont9setWeightEi \
      _ZN5QFont9setWeightEi

$o _ZN2QT19QAbstractScrollArea18setViewportMarginsEiiii \
      _ZN19QAbstractScrollArea18setViewportMarginsEiiii

$o _ZN2QT15QTreeWidgetItemC1Ei \
      _ZN15QTreeWidgetItemC1Ei

$o _ZN2QT8QPainter11drawPolygonEPKNS_7QPointFEiNS_2Qt8FillRuleE \
      _ZN8QPainter11drawPolygonEPK7QPointFiN2Qt8FillRuleE

$o _ZN2QT18QAbstractItemModel15beginRemoveRowsERKNS_11QModelIndexEii \
      _ZN18QAbstractItemModel15beginRemoveRowsERK11QModelIndexii

$o _ZNK2QT12QApplication10styleSheetEv \
      _ZNK12QApplication10styleSheetEv

$o _ZN2QT9QTreeView11qt_metacastEPKc \
      _ZN9QTreeView11qt_metacastEPKc

$o _ZN2QT7QTabBar9insertTabEiRKNS_7QStringE \
      _ZN7QTabBar9insertTabEiRK7QString

$o _ZN2QT9QSplitterC2EPNS_7QWidgetE \
      _ZN9QSplitterC1EP7QWidget

$o _ZNK2QT7QAction7toolTipEv \
      _ZNK7QAction7toolTipEv

$o _ZN2QT10QTransform9translateEdd \
      _ZN10QTransform9translateEdd

$o _ZN2QT5QDrag11setMimeDataEPNS_9QMimeDataE \
      _ZN5QDrag11setMimeDataEP9QMimeData

$o _ZNK2QT9QTextLine9cursorToXEPiNS0_4EdgeE \
      _ZNK9QTextLine9cursorToXEPiNS_4EdgeE

$o _ZN2QT11QPushButtonC1ERKNS_7QStringEPNS_7QWidgetE \
      _ZN11QPushButtonC1ERK7QStringP7QWidget

$o _ZN2QT9QTextLine13setNumColumnsEi \
      _ZN9QTextLine13setNumColumnsEi

$o _ZN2QT7QCursorD1Ev \
      _ZN7QCursorD1Ev

$o _ZN2QT11QCloseEventC1Ev \
      _ZN11QCloseEventC1Ev

$o _ZN2QT9QSplitter8setSizesERKNS_5QListIiEE \
      _ZN9QSplitter8setSizesERK5QListIiE

$o _ZN2QT5QMenu5clearEv \
      _ZN5QMenu5clearEv

$o _ZN2QT6QImage4fillERKNS_6QColorE \
      _ZN6QImage4fillERK6QColor

$o _ZNK2QT14QPlainTextEdit17blockBoundingRectERKNS_10QTextBlockE \
      _ZNK14QPlainTextEdit17blockBoundingRectERK10QTextBlock

$o _ZNK2QT11QListWidget4itemEi \
      _ZNK11QListWidget4itemEi

$o _ZN2QT9QSplitterD2Ev \
      _ZN9QSplitterD2Ev

$o _ZNK2QT15QAbstractButton4textEv \
      _ZNK15QAbstractButton4textEv

$o _ZNK2QT5QFontcvNS_8QVariantEEv \
      _ZNK5QFontcv8QVariantEv

$o _ZN2QT7QWidget10addActionsENS_5QListIPNS_7QActionEEE \
      _ZN7QWidget10addActionsE5QListIP7QActionE

echo $LINENO

$o _ZN2QT9QLineEdit6insertERKNS_7QStringE \
      _ZN9QLineEdit6insertERK7QString

$o _ZN2QT7QWidget17setAccessibleNameERKNS_7QStringE \
      _ZN7QWidget17setAccessibleNameERK7QString

$o _ZN2QT12QApplication10allWidgetsEv \
      _ZN12QApplication10allWidgetsEv

$o _ZN2QT5QFontC1Ev \
      _ZN5QFontC1Ev

$o _ZN2QT9QMetaType25registerNormalizedTypedefERKNS_10QByteArrayEi \
      _ZN9QMetaType25registerNormalizedTypedefERK10QByteArrayS_

$o _ZN9QMetaType25registerNormalizedTypedefERK10QByteArrayS_ \
   _ZN9QMetaType25registerNormalizedTypedefERK10QByteArrayi

$o _ZN2QT12QApplication13setStyleSheetERKNS_7QStringE \
      _ZN12QApplication13setStyleSheetERK7QString

$o _ZN2QT11QHeaderView26setCascadingSectionResizesEb \
      _ZN11QHeaderView26setCascadingSectionResizesEb

$o _ZN2QT9QSplitter22setChildrenCollapsibleEb \
      _ZN9QSplitter22setChildrenCollapsibleEb

$o _ZN2QT5QMenuC1EPNS_7QWidgetE \
      _ZN5QMenuC1EP7QWidget

$o _ZNK2QT11QTextCursor14selectionStartEv \
      _ZNK11QTextCursor14selectionStartEv

$o _ZNK2QT9QMimeData4dataERKNS_7QStringE \
      _ZNK9QMimeData4dataERK7QString

$o _ZNK2QT19QItemSelectionModel15selectedIndexesEv \
      _ZNK19QItemSelectionModel15selectedIndexesEv

$o _ZN2QT11QTreeWidget13setHeaderItemEPNS_15QTreeWidgetItemE \
      _ZN11QTreeWidget13setHeaderItemEP15QTreeWidgetItem

$o _ZNK2QT9QTextLine10textLengthEv \
      _ZNK9QTextLine10textLengthEv

$o _ZN2QT12QTableWidget7setItemEiiPNS_16QTableWidgetItemE \
      _ZN12QTableWidget7setItemEiiP16QTableWidgetItem

$o _ZN2QT7QTabBar10setTabTextEiRKNS_7QStringE \
      _ZN7QTabBar10setTabTextEiRK7QString

$o _ZN2QT9QTreeView20setUniformRowHeightsEb \
      _ZN9QTreeView20setUniformRowHeightsEb

$o _ZN2QT6QTimer5startEi \
      _ZN6QTimer5startEi

$o _ZN2QT12QApplication7desktopEv \
      _ZN12QApplication7desktopEv

$o _ZN2QT19QAbstractScrollAreaD2Ev \
      _ZN19QAbstractScrollAreaD2Ev

$o _ZNK2QT6QColor6darkerEi \
      _ZNK6QColor6darkerEi

$o _ZNK2QT11QTextLayout12boundingRectEv \
      _ZNK11QTextLayout12boundingRectEv

$o _ZNK2QT9QComboBox11currentTextEv \
      _ZNK9QComboBox11currentTextEv

$o _ZN2QT11QRubberBand11setGeometryERKNS_5QRectE \
      _ZN11QRubberBand11setGeometryERK5QRect

$o _ZN2QT11QTextCursor10deleteCharEv \
      _ZN11QTextCursor10deleteCharEv

$o _ZNK2QT14QPlainTextEdit8documentEv \
      _ZNK14QPlainTextEdit8documentEv

$o _ZN2QT10QTabWidget10setTabTextEiRKNS_7QStringE \
      _ZN10QTabWidget10setTabTextEiRK7QString

$o _ZN2QT11QMainWindow11qt_metacastEPKc \
      _ZN11QMainWindow11qt_metacastEPKc

$o _ZN2QT11QMainWindowC2EPNS_7QWidgetENS_6QFlagsINS_2Qt10WindowTypeEEE \
      _ZN11QMainWindowC2EP7QWidget6QFlagsIN2Qt10WindowTypeEE

$o _ZN2QT5QChar7toUpperEj \
      _ZN5QChar7toUpperEj

$o _ZNK2QT9QSettings5valueERKNS_7QStringERKNS_8QVariantE \
      _ZNK9QSettings5valueERK7QStringRK8QVariant

echo $LINENO

$o _ZN2QT15QTreeWidgetItemD2Ev \
      _ZN15QTreeWidgetItemD2Ev

$o _ZN2QT5QFont8setStyleENS0_5StyleE \
      _ZN5QFont8setStyleENS_5StyleE

$o _ZNK2QT12QTableWidget6columnEPKNS_16QTableWidgetItemE \
      _ZNK12QTableWidget6columnEPK16QTableWidgetItem

$o _ZN2QT9QSplitter16setStretchFactorEii \
      _ZN9QSplitter16setStretchFactorEii

$o _ZN2QT7QBitmapD1Ev \
      _ZN7QBitmapD1Ev

$o _ZN2QT11QTextFormat11setPropertyEiRKNS_8QVariantE \
      _ZN11QTextFormat11setPropertyEiRK8QVariant

$o _ZNK2QT7QTabBar10tabToolTipEi \
      _ZNK7QTabBar10tabToolTipEi

$o _ZN2QT15QAbstractButton13setAutoRepeatEb \
      _ZN15QAbstractButton13setAutoRepeatEb

$o _ZNK2QT11QHeaderView5countEv \
      _ZNK11QHeaderView5countEv

$o _ZN2QT9QCheckBoxC1ERKNS_7QStringEPNS_7QWidgetE \
      _ZN9QCheckBoxC1ERK7QStringP7QWidget

$o _ZNK2QT5QIconcvNS_8QVariantEEv \
      _ZNK5QIconcv8QVariantEv

$o _ZN2QT7QAction7setIconERKNS_5QIconE \
      _ZN7QAction7setIconERK5QIcon

$o _ZN2QT16QCoreApplication18removePostedEventsEPNS_7QObjectEi \
      _ZN16QCoreApplication18removePostedEventsEP7QObjecti

$o _ZN2QT9QListData6appendEv \
      _ZN9QListData6appendEv

$o _ZNK2QT14QPlainTextEdit17firstVisibleBlockEv \
      _ZNK14QPlainTextEdit17firstVisibleBlockEv

$o _ZN2QT7QObjectC2EPS0_ \
      _ZN7QObjectC2EPS_

$o _ZN2QT7QWidget17setUpdatesEnabledEb \
      _ZN7QWidget17setUpdatesEnabledEb

$o _ZN2QT16QCoreApplication18setApplicationNameERKNS_7QStringE \
      _ZN16QCoreApplication18setApplicationNameERK7QString

$o _ZN2QT6QLabel11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN6QLabel11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZNK2QT9QTextLine6heightEv \
      _ZNK9QTextLine6heightEv

$o _ZNK2QT16QDialogButtonBox14standardButtonEPNS_15QAbstractButtonE \
      _ZNK16QDialogButtonBox14standardButtonEP15QAbstractButton

$o _ZN2QT7QString6resizeEi \
      _ZN7QString6resizeEi

$o _ZNK2QT7QWidget11mapToGlobalERKNS_6QPointE \
      _ZNK7QWidget11mapToGlobalERK6QPoint

$o _ZN2QT9QGroupBox11qt_metacastEPKc \
      _ZN9QGroupBox11qt_metacastEPKc

$o _ZN2QTrsERNS_11QDataStreamERNS_5QRectE \
           _ZrsR11QDataStreamR5QRect

$o _ZNK2QT7QScreen8geometryEv \
      _ZNK7QScreen8geometryEv

$o _ZN2QT6QFrame11qt_metacastEPKc \
      _ZN6QFrame11qt_metacastEPKc

$o _ZN2QT11QGridLayout9addLayoutEPNS_7QLayoutEiiiiNS_6QFlagsINS_2Qt13AlignmentFlagEEE \
      _ZN11QGridLayout9addLayoutEP7QLayoutii6QFlagsIN2Qt13AlignmentFlagEE

$o _ZN2QT9QGroupBox7setFlatEb \
      _ZN9QGroupBox7setFlatEb

$o _ZNK2QT13QTextDocument10isModifiedEv \
      _ZNK13QTextDocument10isModifiedEv

$o _ZN2QT11QTextStreamD1Ev \
      _ZN11QTextStreamD1Ev

$o _ZNK2QT9QComboBox9completerEv \
      _ZNK9QComboBox9completerEv

$o _ZN2QT8QPainter15drawRoundedRectERKNS_6QRectFEddNS_2Qt8SizeModeE \
      _ZN8QPainter15drawRoundedRectERK6QRectFddN2Qt8SizeModeE

echo $LINENO

$o _ZN2QT12QMapDataBase10createDataEv \
      _ZN12QMapDataBase10createDataEv

$o _ZN2QT11QWheelEventD1Ev \
      _ZN11QWheelEventD1Ev

$o _ZN2QT12QApplication4beepEv \
      _ZN12QApplication4beepEv

$o _ZN2QT9QSettingsD1Ev \
      _ZN9QSettingsD1Ev

$o _ZN2QT11QListWidget8takeItemEi \
      _ZN11QListWidget8takeItemEi

$o _ZNK2QT7QAction9isVisibleEv \
      _ZNK7QAction9isVisibleEv

$o _ZN2QT9QTreeViewD2Ev \
      _ZN9QTreeViewD2Ev

$o _ZNK2QT9QSplitter11orientationEv \
      _ZNK9QSplitter11orientationEv

$o _ZN2QT11QHeaderView20setSectionsClickableEb \
      _ZN11QHeaderView20setSectionsClickableEb

$o _ZNK2QT11QTextCursor12selectedTextEv \
      _ZNK11QTextCursor12selectedTextEv

$o _ZN2QT7QActionC2EPNS_7QObjectE \
      _ZN7QActionC2EP7QObject

$o _ZN2QT16QCoreApplication13processEventsENS_6QFlagsINS_10QEventLoop17ProcessEventsFlagEEE \
      _ZN16QCoreApplication13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE

$o _ZNK2QT7QString4leftEi \
      _ZNK7QString4leftEi

$o _ZNK2QT11QPageLayout15paintRectPixelsEi \
      _ZNK2QT11QPageLayout15paintRectPixelsEi

$o _ZNK2QT11QPageLayout15paintRectPixelsEi \
      _ZNK11QPageLayout15paintRectPixelsEi

$o _ZNK2QT7QString7indexOfERNS_7QRegExpEi \
      _ZNK7QString7indexOfERK7QRegExpi

$o _ZN2QT6QTimer10singleShotEiPKNS_7QObjectEPKc \
      _ZN6QTimer10singleShotEiPK7QObjectPKc

$o _ZN2QT9QHashData13detach_helperEPFvPNS0_4NodeEPvEPFvS2_Eii \
      _ZN9QHashData13detach_helperEPFvPNS_4NodeEPvEPFvS1_Eii

$o _ZN2QT13QFontMetricsFD1Ev \
      _ZN12QFontMetricsD1Ev

$o _ZNK2QT11QPushButton15initStyleOptionEPNS_18QStyleOptionButtonE \
      _ZNK11QPushButton15initStyleOptionEP18QStyleOptionButton

$o _ZNK2QT9QComboBox8findDataERKNS_8QVariantEiNS_6QFlagsINS_2Qt9MatchFlagEEE \
      _ZNK9QComboBox8findDataERK8QVarianti6QFlagsIN2Qt9MatchFlagEE

$o _ZN2QT7QString11reallocDataEjb \
      _ZN7QString11reallocDataEjb

$o _ZNK2QT7QWidget5mapToEPKS0_RKNS_6QPointE \
      _ZNK7QWidget5mapToEPKS_RK6QPoint

$o _ZN2QT9QGroupBoxC1ERKNS_7QStringEPNS_7QWidgetE \
      _ZN2QT9QGroupBoxC1ERKNS_7QStringEPNS_7QWidgetE

$o _ZN2QT9QGroupBoxC1ERKNS_7QStringEPNS_7QWidgetE \
      _ZN9QGroupBoxC1ERK7QStringP7QWidget

$o _ZNK2QT11QTreeWidget13selectedItemsEv \
      _ZNK11QTreeWidget13selectedItemsEv

$o _ZN2QT5QIconC1ERKNS_7QStringE \
      _ZN5QIconC1ERK7QString

$o _ZN2QT11QDockWidget11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN11QDockWidget11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZNK2QT4QUrl11toLocalFileEv \
      _ZNK4QUrl11toLocalFileEv

$o _ZN2QT5QDragC1EPNS_7QObjectE \
      _ZN5QDragC1EP7QObject

$o _ZN2QT14QItemSelection5mergeERKS0_NS_6QFlagsINS_19QItemSelectionModel13SelectionFlagEEE \
      _ZN14QItemSelection5mergeERKS_6QFlagsIN19QItemSelectionModel13SelectionFlagEE

$o _ZN2QT18QAbstractListModelD2Ev \
      _ZN18QAbstractListModelD2Ev

$o _ZNK2QT15QAbstractSlider7minimumEv \
      _ZNK15QAbstractSlider7minimumEv

echo $LINENO

$o _ZN2QT11QTextLayout7setTextERKNS_7QStringE \
      _ZN11QTextLayout7setTextERK7QString

$o _ZN2QT9QMimeData7setDataERKNS_7QStringERKNS_10QByteArrayE \
      _ZN9QMimeData7setDataERK7QStringRK10QByteArray

$o _ZNK2QT7QAction4dataEv \
      _ZNK7QAction4dataEv

$o _ZN2QT12QTableWidgetC2EPNS_7QWidgetE \
      _ZN12QTableWidgetC1EP7QWidget

$o _ZN2QT9QTreeViewC2EPNS_7QWidgetE \
      _ZN9QTreeViewC2EP7QWidget

$o _ZN2QT7QLocaleaSERKS0_ \
      _ZN7QLocaleaSERKS_

$o _ZN2QT11QFontDialog11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN11QFontDialog11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZNK2QT15QTreeWidgetItem18executePendingSortEv \
      _ZNK15QTreeWidgetItem18executePendingSortEv

$o _ZN2QT18QSyntaxHighlighter11qt_metacastEPKc \
      _ZN18QSyntaxHighlighter11qt_metacastEPKc

$o _ZN2QT15QTreeWidgetItemC2EPS0_i \
      _ZN15QTreeWidgetItemC2EPS_i

$o _ZN2QT7QDialogC2EPNS_7QWidgetENS_6QFlagsINS_2Qt10WindowTypeEEE \
      _ZN7QDialogC2EP7QWidget6QFlagsIN2Qt10WindowTypeEE

$o _ZN2QT11QTextOptionC1Ev \
      _ZN11QTextOptionC1Ev

$o _ZNK2QT7QWidget6layoutEv \
      _ZNK7QWidget6layoutEv

$o _ZNK2QT8QPainter8viewportEv \
      _ZNK8QPainter8viewportEv

$o _ZN2QT13QFontMetricsFC1ERKNS_5QFontE \
      _ZN13QFontMetricsFC1ERK5QFont

$o _ZN2QT16QCoreApplication17installTranslatorEPNS_11QTranslatorE \
      _ZN16QCoreApplication17installTranslatorEP11QTranslator

$o _ZN2QT9QKeyEventD1Ev \
      _ZN9QKeyEventD1Ev

$o _ZN2QT19QAbstractScrollArea28setHorizontalScrollBarPolicyENS_2Qt15ScrollBarPolicyE \
      _ZN19QAbstractScrollArea28setHorizontalScrollBarPolicyEN2Qt15ScrollBarPolicyE

$o _ZNK2QT7QObject20dynamicPropertyNamesEv \
      _ZNK7QObject20dynamicPropertyNamesEv

$o _ZN2QT8QToolTip8showTextERKNS_6QPointERKNS_7QStringEPNS_7QWidgetE \
      _ZN8QToolTip8showTextERK6QPointRK7QStringP7QWidget

$o _ZN2QT6QLabelD2Ev \
      _ZN6QLabelD2Ev

$o _ZNK2QT11QTextLayout18nextCursorPositionEiNS0_10CursorModeE \
      _ZNK11QTextLayout18nextCursorPositionEiNS_10CursorModeE

$o _ZN2QT9QTreeView9expandAllEv \
      _ZN9QTreeView9expandAllEv

$o _ZN2QT8QPainter4saveEv \
      _ZN8QPainter4saveEv

$o _ZN2QT8QPainter7setFontERKNS_5QFontE \
      _ZN8QPainter7setFontERK5QFont

$o _ZN2QT7QAction18setShortcutContextENS_2Qt15ShortcutContextE \
      _ZN7QAction18setShortcutContextEN2Qt15ShortcutContextE

$o _ZN2QT6QLabel13setTextFormatENS_2Qt10TextFormatE \
      _ZN6QLabel13setTextFormatEN2Qt10TextFormatE

$o _ZN2QT7QString6removeERKS0_NS_2Qt15CaseSensitivityE \
      _ZN7QString6removeERKS_N2Qt15CaseSensitivityE

$o _ZN2QT19QAbstractScrollAreaC2EPNS_7QWidgetE \
      _ZN19QAbstractScrollAreaC2EP7QWidget

$o _ZNK2QT7QString8endsWithENS_5QCharENS_2Qt15CaseSensitivityE \
      _ZNK7QString8endsWithE5QCharN2Qt15CaseSensitivityE

$o _ZN2QT7QWidget11setTabOrderEPS0_S1_ \
      _ZN7QWidget11setTabOrderEPS_S0_

$o _ZN2QT7QString18toLocal8Bit_helperEPKNS_5QCharEi \
      _ZN7QString18toLocal8Bit_helperEPK5QChari

echo $LINENO

$o _ZN2QT6QTimer5startEv \
      _ZN6QTimer5startEv

$o _ZN2QT6QBrushC1Ev \
      _ZN6QBrushC1Ev

$o _ZNK2QT17QAbstractItemView18verticalScrollModeEv \
      _ZNK17QAbstractItemView18verticalScrollModeEv

$o _ZN2QT8QSpinBoxC1EPNS_7QWidgetE \
      _ZN8QSpinBoxC1EP7QWidget

$o _ZN2QT14QPlainTextEdit10appendHtmlERKNS_7QStringE \
      _ZN14QPlainTextEdit10appendHtmlERK7QString

$o _ZN2QTltERKNS_7QStringES2_ \
      _ZltRK7QStringS1_

$o _ZNK2QT9QLineEdit4textEv \
      _ZNK9QLineEdit4textEv

$o _ZN2QT11QMessageBox13setTextFormatENS_2Qt10TextFormatE \
      _ZN11QMessageBox13setTextFormatEN2Qt10TextFormatE

$o _ZN2QT7QAction12setShortcutsERKNS_5QListINS_12QKeySequenceEEE \
      _ZN7QAction12setShortcutsERK5QListI12QKeySequenceE

$o _ZN2QT9QComboBox15setCurrentIndexEi \
      _ZN9QComboBox15setCurrentIndexEi

$o _ZN2QT11QHBoxLayoutC1EPNS_7QWidgetE \
      _ZN11QHBoxLayoutC1EP7QWidget

$o _ZNK2QT14QPlainTextEdit10textCursorEv \
      _ZNK14QPlainTextEdit10textCursorEv

$o _ZNK2QT11QMetaObject4castEPNS_7QObjectE \
      _ZNK11QMetaObject4castEPK7QObject

$o _ZN2QT7QTabBar15setTabsClosableEb \
      _ZN7QTabBar15setTabsClosableEb

$o _ZNK2QT7QString3midEii \
      _ZNK7QString3midEii

$o _ZN2QT7QObject9setParentEPS0_ \
      _ZN7QObject9setParentEPS_

$o _ZNK2QT9QComboBox5countEv \
      _ZNK9QComboBox5countEv

$o _ZN2QT11QTreeWidget11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN11QTreeWidget11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT6QEventD2Ev \
      _ZN6QEventD2Ev

$o _ZNK2QT12QTableWidget4itemEii \
      _ZNK12QTableWidget4itemEii

$o _ZN2QT7QDialog11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN7QDialog11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZNK2QT11QFocusEvent6reasonEv \
      _ZNK11QFocusEvent6reasonEv

$o _ZN2QT7QWidget14setFocusPolicyENS_2Qt11FocusPolicyE \
      _ZN7QWidget14setFocusPolicyEN2Qt11FocusPolicyE

$o _ZN2QT10QTabWidget6addTabEPNS_7QWidgetERKNS_7QStringE \
      _ZN10QTabWidget6addTabEP7QWidgetRK7QString

$o _ZN2QT11QListWidget13setCurrentRowEi \
      _ZN11QListWidget13setCurrentRowEi

$o _ZN2QT15QTreeWidgetItem11setSelectedEb \
      _ZN15QTreeWidgetItem11setSelectedEb

$o _ZN2QT19QAbstractScrollArea11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN19QAbstractScrollArea11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT6QFrame13setFrameShapeENS0_5ShapeE \
      _ZN6QFrame13setFrameShapeENS_5ShapeE

$o _ZN2QT11QGridLayoutC1Ev \
      _ZN11QGridLayoutC1Ev

$o _ZN2QT11QFontDialog9setOptionENS0_16FontDialogOptionEb \
      _ZN11QFontDialog9setOptionENS_16FontDialogOptionEb

$o _ZN2QT6QLabel20setOpenExternalLinksEb \
      _ZN6QLabel20setOpenExternalLinksEb

$o _ZN2QT5QFont13setPointSizeFEd \
      _ZN5QFont13setPointSizeFEd

$o _ZNK2QT11QTextLayout6lineAtEi \
      _ZNK11QTextLayout6lineAtEi

echo $LINENO

$o _ZN2QT8QSpinBox10setMaximumEi \
      _ZN8QSpinBox10setMaximumEi

$o _ZN2QT15QAbstractButton18setAutoRepeatDelayEi \
      _ZN15QAbstractButton18setAutoRepeatDelayEi

$o _ZN2QT6QColor8fromRgbaEj \
      _ZN6QColor8fromRgbaEj

$o _ZN2QT11QPushButtonD2Ev \
      _ZN11QPushButtonD2Ev

$o _ZN2QT5QFileC1ERKNS_7QStringE \
      _ZN5QFileC1ERK7QString

$o _ZN2QT6QBrushaSERKS0_ \
      _ZN6QBrushaSERKS_

$o _ZN2QT16QCoreApplication21setOrganizationDomainERKNS_7QStringE \
      _ZN16QCoreApplication21setOrganizationDomainERK7QString

$o _ZNK2QT7QAction4textEv \
      _ZNK7QAction4textEv

$o _ZN2QT7QRegExpC1ERKNS_7QStringENS_2Qt15CaseSensitivityENS0_13PatternSyntaxE \
      _ZN7QRegExpC1ERK7QStringN2Qt15CaseSensitivityENS_13PatternSyntaxE

$o _ZN2QT11QDataStreamC1EPNS_10QByteArrayENS_6QFlagsINS_9QIODevice12OpenModeFlagEEE \
      _ZN11QDataStreamC1EP10QByteArray6QFlagsIN9QIODevice12OpenModeFlagEE

$o _ZNK2QT7QRegion10subtractedERKS0_ \
      _ZNK7QRegion10subtractedERKS_

$o _ZNK2QT15QAbstractSlider12isSliderDownEv \
      _ZNK15QAbstractSlider12isSliderDownEv

$o _ZN2QT11QPushButtonC2EPNS_7QWidgetE \
      _ZN11QPushButtonC2EP7QWidget

$o _ZN2QT15QAbstractButton21setAutoRepeatIntervalEi \
      _ZN15QAbstractButton21setAutoRepeatIntervalEi

$o _ZN2QT12QTableWidget14setColumnCountEi \
      _ZN12QTableWidget14setColumnCountEi

$o _ZN2QT11QMainWindow16setCentralWidgetEPNS_7QWidgetE \
      _ZN11QMainWindow16setCentralWidgetEP7QWidget

$o _ZN2QT15QGuiApplication8screenAtERKNS_6QPointE \
      _ZN15QGuiApplication8screenAtERK6QPoint

$o _ZN2QT7QString7replaceENS_5QCharES1_NS_2Qt15CaseSensitivityE \
      _ZN7QString7replaceE5QCharS0_N2Qt15CaseSensitivityE

$o _ZN2QT10QStatusBar12clearMessageEv \
      _ZN10QStatusBar12clearMessageEv

$o _ZN2QT5QFont12setUnderlineEb \
      _ZN5QFont12setUnderlineEb

$o _ZNK2QT6QImage4sizeEv \
      _ZNK6QImage4sizeEv

$o _ZN2QT8QPainter8fillRectERKNS_5QRectERKNS_6QColorE \
      _ZN8QPainter8fillRectERK5QRectRK6QColor

$o _ZN2QT8QPainterC1Ev \
      _ZN8QPainterC1Ev

$o _ZN2QT7QWidget10setEnabledEb \
      _ZN7QWidget10setEnabledEb

$o _ZN2QT10QTransform6rotateEdNS_2Qt4AxisE \
      _ZN10QTransform6rotateEdN2Qt4AxisE

$o _ZN2QT7QString7replaceERKS0_S2_NS_2Qt15CaseSensitivityE \
      _ZN7QString7replaceERKS_S1_N2Qt15CaseSensitivityE

$o _ZN2QT9QSplitter14setOrientationENS_2Qt11OrientationE \
      _ZN9QSplitter14setOrientationEN2Qt11OrientationE

$o _ZNK2QT11QListWidget10currentRowEv \
      _ZNK11QListWidget10currentRowEv

$o _ZN2QT9QHashData6rehashEi \
      _ZN9QHashData6rehashEi

$o _ZN2QT12QPrintDialogC1EPNS_8QPrinterEPNS_7QWidgetE \
      _ZN12QPrintDialogC1EP8QPrinterP7QWidget

$o _ZNK2QT7QString7indexOfERKS0_iNS_2Qt15CaseSensitivityE \
      _ZNK7QString7indexOfERKS_xN2Qt15CaseSensitivityE

$o _ZNK7QString7indexOfERKS_xN2Qt15CaseSensitivityE \
   _ZN12QPrintDialogC1EP8QPrinterP7QWidget # imposible reemplazar

$o _ZNK2QT11QObjectData17dynamicMetaObjectEv \
      _ZNK11QObjectData17dynamicMetaObjectEv

echo $LINENO

$o _ZN2QT6QImageD1Ev \
      _ZN6QImageD1Ev

$o _ZN2QT6QLabel11setWordWrapEb \
      _ZN6QLabel11setWordWrapEb

$o _ZN2QT5QDrag9setPixmapERKNS_7QPixmapE \
      _ZN5QDrag9setPixmapERK7QPixmap

$o _ZN2QT11QGridLayout9addWidgetEPNS_7QWidgetEiiiiNS_6QFlagsINS_2Qt13AlignmentFlagEEE \
      _ZN11QGridLayout9addWidgetEP7QWidgetii6QFlagsIN2Qt13AlignmentFlagEE

$o _ZN2QT11QDockWidgetD2Ev \
      _ZN11QDockWidgetD2Ev

$o _ZN2QT7QWidget4moveERKNS_6QPointE \
      _ZN7QWidget4moveERK6QPoint

$o _ZN2QT12QTableWidget25setHorizontalHeaderLabelsERKNS_11QStringListE \
      _ZN12QTableWidget25setHorizontalHeaderLabelsERK11QStringList

$o _ZN2QT12QTableWidget25setHorizontalHeaderLabelsERKNS_11QStringListE \
      _ZN12QTableWidget25setHorizontalHeaderLabelsERK11QStringList

$o _ZNK2QT9QGroupBox5titleEv \
      _ZNK9QGroupBox5titleEv

$o _ZN2QT7QWidget10showNormalEv \
      _ZN7QWidget10showNormalEv

$o _ZNK2QT11QTextLayout4textEv \
      _ZNK11QTextLayout4textEv

$o _ZN2QT7QWidget13setFixedWidthEi \
      _ZN7QWidget13setFixedWidthEi

$o _ZNK2QT11QMessageBox13clickedButtonEv \
      _ZNK11QMessageBox13clickedButtonEv

$o _ZN2QT5qHashERKNS_7QStringEj \
      _Z5qHashRK7QStringj

$o _ZN2QT9QComboBox10insertItemEiRKNS_5QIconERKNS_7QStringERKNS_8QVariantE \
      _ZN9QComboBox10insertItemEiRK5QIconRK7QStringRK8QVariant

$o _ZNK2QT11QTextLayout9lineCountEv \
      _ZNK11QTextLayout9lineCountEv

$o _ZN2QT9QShortcutC1ERKNS_12QKeySequenceEPNS_7QWidgetEPKcS7_NS_2Qt15ShortcutContextE \
      _ZN9QShortcutC1ERK12QKeySequenceP7QWidgetPKcS6_N2Qt15ShortcutContextE

$o _ZN2QT9QShortcutC1ERKNS_12QKeySequenceEPNS_7QWidgetEPKcS7_NS_2Qt15ShortcutContextE \
      _ZN9QShortcutC1ERK12QKeySequenceP7QWidgetPKcS6_N2Qt15ShortcutContextE

$o _ZN2QT11QGridLayout9addWidgetEPNS_7QWidgetEiiNS_6QFlagsINS_2Qt13AlignmentFlagEEE \
      _ZN11QGridLayout9addWidgetEP7QWidgetii6QFlagsIN2Qt13AlignmentFlagEE

$o _ZNK2QT7QString5toIntEPbi \
      _ZNK7QString5toIntEPbi

$o _ZNK2QT9QSplitter6widgetEi \
      _ZNK9QSplitter6widgetEi

$o _ZN2QT7QWidget13showMaximizedEv \
      _ZN7QWidget13showMaximizedEv

$o _ZN2QT9QComboBox19setSizeAdjustPolicyENS0_16SizeAdjustPolicyE \
      _ZN9QComboBox19setSizeAdjustPolicyENS_16SizeAdjustPolicyE

$o _ZNK2QT9QLineEdit14selectionStartEv \
      _ZNK9QLineEdit14selectionStartEv

$o _ZN2QT11QTextCursor12movePositionENS0_13MoveOperationENS0_8MoveModeEi \
      _ZN11QTextCursor12movePositionENS_13MoveOperationENS_8MoveModeEi

$o _ZNK2QT7QTabBar7tabRectEi \
      _ZNK7QTabBar7tabRectEi

$o _ZN2QT9QFontInfoD1Ev \
      _ZN9QFontInfoD1Ev

$o _ZN2QT8QVariantC1ERKNS_11QStringListE \
      _ZN8QVariantC1ERK11QStringList

$o _ZN2QT12QApplication17activeModalWidgetEv \
      _ZN12QApplication17activeModalWidgetEv

$o _ZNK2QT5QIcon6pixmapERKNS_5QSizeENS0_4ModeENS0_5StateE \
      _ZNK5QIcon6pixmapERK5QSizeNS_4ModeENS_5StateE

$o _ZNK2QT7QPixmap5widthEv \
      _ZNK7QPixmap5widthEv

$o _ZN2QT4QPenC1ERKS0_ \
      _ZN4QPenC1ERKS_

echo $LINENO

$o _ZN2QT11QTextLayoutC1ERKNS_7QStringERKNS_5QFontEPNS_12QPaintDeviceE \
      _ZN11QTextLayoutC1ERK7QStringRK5QFontP12QPaintDevice

$o _ZN2QT9QLineEdit9selectAllEv \
      _ZN9QLineEdit9selectAllEv

$o _ZN2QT12QStyleOptionaSERKS0_ \
      _ZN12QStyleOptionaSERKS_

$o _ZN2QT11QMainWindow11qt_metacallENS_11QMetaObject4CallEiPPv \
      _ZN11QMainWindow11qt_metacallEN11QMetaObject4CallEiPPv

$o _ZN2QT17QAccessibleWidgetC2EPNS_7QWidgetENS_11QAccessible4RoleERKNS_7QStringE \
      _ZN17QAccessibleWidgetC2EP7QWidgetN11QAccessible4RoleERK7QString

$o _ZN2QT10QTableView12sortByColumnEiNS_2Qt9SortOrderE \
      _ZN10QTableView12sortByColumnEiN2Qt9SortOrderE

$o _ZN2QT7QLocaleC1Ev \
      _ZN7QLocaleC1Ev

$o _ZN2QT18QSyntaxHighlighter20setCurrentBlockStateEi \
      _ZN18QSyntaxHighlighter20setCurrentBlockStateEi

$o _ZNK2QT9QFileInfo16absoluteFilePathEv \
      _ZNK9QFileInfo16absoluteFilePathEv

$o _ZN2QT11QVBoxLayoutC1EPNS_7QWidgetE \
      _ZN11QVBoxLayoutC1EP7QWidget

$o _ZN2QT15QGuiApplication21restoreOverrideCursorEv \
      _ZN15QGuiApplication21restoreOverrideCursorEv

$o _ZN2QT7QWidget15setMinimumWidthEi \
      _ZN7QWidget15setMinimumWidthEi

$o _ZNK2QT11QDockWidget8featuresEv \
      _ZNK11QDockWidget8featuresEv

$o _ZN2QT7QCursorC1ENS_2Qt11CursorShapeE \
      _ZN7QCursorC1EN2Qt11CursorShapeE

$o _ZN2QT10QArrayData8allocateEmmmNS_6QFlagsINS0_16AllocationOptionEEE \
      _ZN10QArrayData8allocateEmmm6QFlagsINS_16AllocationOptionEE

$o _ZN2QT6QEventC1ENS0_4TypeE \
      _ZN6QEventC1ENS_4TypeE

$o _ZNK2QT17QAbstractItemView9rootIndexEv \
      _ZNK17QAbstractItemView9rootIndexEv

$o _ZNK2QT9QTreeView16isSortingEnabledEv \
      _ZNK9QTreeView16isSortingEnabledEv

$o _ZN2QT7QAction12setStatusTipERKNS_7QStringE \
      _ZN7QAction12setStatusTipERK7QString

$o _ZN2QT7QWidget16setMinimumHeightEi \
      _ZN7QWidget16setMinimumHeightEi

$o _ZNK2QT11QMetaObject9classNameEv \
      _ZNK11QMetaObject9classNameEv

$o _ZN2QT8QPainter7restoreEv \
      _ZN8QPainter7restoreEv

$o _ZN2QT7QTabBar10setMovableEb \
      _ZN7QTabBar10setMovableEb

$o _ZN2QT4QPenC1ERKNS_6QColorE \
      _ZN4QPenC1ERK6QColor

$o _ZNK2QT11QTextLayout19lineForTextPositionEi \
      _ZNK11QTextLayout19lineForTextPositionEi

$o _ZN2QT11QDataStreamlsEi \
      _ZN11QDataStreamlsEi

$o _ZN2QT6QFrame13setFrameStyleEi \
      _ZN6QFrame13setFrameStyleEi

$o _ZN2QT6QFrameC1EPNS_7QWidgetENS_6QFlagsINS_2Qt10WindowTypeEEE \
      _ZN6QFrameC2EP7QWidget6QFlagsIN2Qt10WindowTypeEE

$o _ZN2QT10QBoxLayout10setSpacingEi \
      _ZN10QBoxLayout10setSpacingEi

$o _ZNK2QT6QLabel4textEv \
      _ZNK6QLabel4textEv

$o _ZNK2QT9QTextLine16naturalTextWidthEv \
      _ZNK9QTextLine16naturalTextWidthEv

$o _ZNK2QT7QAction9shortcutsEv \
      _ZNK7QAction9shortcutsEv

$o _ZN2QT11QGridLayout13setRowStretchEii \
      _ZN11QGridLayout13setRowStretchEii

echo $LINENO

$o _ZN2QT23qt_qFindChildren_helperEPKNS_7QObjectERKNS_7QStringERKNS_11QMetaObjectEPNS_5QListIPvEENS_6QFlagsINS_2Qt15FindChildOptionEEE \
      _Z23qt_qFindChildren_helperPK7QObjectRK7QStringRK11QMetaObjectP5QListIPvE6QFlagsIN2Qt15FindChildOptionEE

$o _ZNK2QT10QTextBlock11blockNumberEv \
      _ZNK10QTextBlock11blockNumberEv

$o _ZN2QT9QTreeView17setSortingEnabledEb \
      _ZN9QTreeView17setSortingEnabledEb

$o _ZNK2QT8QVariant11toByteArrayEv \
      _ZNK8QVariant11toByteArrayEv

$o _ZNK2QT5QFont9pointSizeEv \
      _ZNK5QFont9pointSizeEv

$o _ZN2QT11QTreeWidgetD2Ev \
      _ZN11QTreeWidgetD2Ev

$o _ZNK2QT11QHeaderView15isSectionHiddenEi \
      _ZNK11QHeaderView15isSectionHiddenEi

$o _ZN2QT11QPushButton11qt_metacastEPKc \
      _ZN11QPushButton11qt_metacastEPKc

$o _ZN2QT10QStatusBar18setSizeGripEnabledEb \
      _ZN10QStatusBar18setSizeGripEnabledEb

$o _ZN2QT9QMetaType30hasRegisteredConverterFunctionEii \
      _ZN9QMetaType30hasRegisteredConverterFunctionEii

$o _ZN2QT8QPrinter7newPageEv \
      _ZN8QPrinter7newPageEv

$o _ZNK2QT7QString8endsWithERKS0_NS_2Qt15CaseSensitivityE \
      _ZNK7QString8endsWithE5QCharN2Qt15CaseSensitivityE

$o _ZN2QT8QPrinterC1ENS0_11PrinterModeE \
      _ZN8QPrinterC1ENS_11PrinterModeE

$o _ZN2QT9QListData6detachEi \
      _ZN9QListData6detachEi

$o _ZNK2QT11QMainWindow7menuBarEv \
      _ZNK11QMainWindow7menuBarEv

$o _ZNK2QT17QAbstractItemView12editTriggersEv \
      _ZNK17QAbstractItemView12editTriggersEv

$o _ZN2QT7QPixmap12loadFromDataEPKhjPKcNS_6QFlagsINS_2Qt19ImageConversionFlagEEE \
      _ZN7QPixmap12loadFromDataEPKhjPKc6QFlagsIN2Qt19ImageConversionFlagEE

$o _ZNK2QT12QKeySequenceeqERKS0_ \
      _ZNK12QKeySequenceeqERKS_

$o _ZN2QT8QPainter11setClipRectERKNS_5QRectENS_2Qt13ClipOperationE \
      _ZN8QPainter11setClipRectERK5QRectN2Qt13ClipOperationE

$o _ZNK2QT17QAccessibleWidget4textENS_11QAccessible4TextE \
      _ZNK17QAccessibleWidget4textEN11QAccessible4TextE

$o _ZN2QT11QDataStreamrsERi \
      _ZN11QDataStreamrsERi

/opt/ida-free/ida64 2>&1 | sed "s/[,:]/\n/g" | grep _Z
exit
